/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InternalImagesHandlerUploadInitRequest model module.
 * @module models/InternalImagesHandlerUploadInitRequest
 * @version 2.0.0
 */
class InternalImagesHandlerUploadInitRequest {
    /**
     * Constructs a new <code>InternalImagesHandlerUploadInitRequest</code>.
     * @alias module:models/InternalImagesHandlerUploadInitRequest
     */
    constructor() { 
        
        InternalImagesHandlerUploadInitRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InternalImagesHandlerUploadInitRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/InternalImagesHandlerUploadInitRequest} obj Optional instance to populate.
     * @return {module:models/InternalImagesHandlerUploadInitRequest} The populated <code>InternalImagesHandlerUploadInitRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InternalImagesHandlerUploadInitRequest();

            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InternalImagesHandlerUploadInitRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InternalImagesHandlerUploadInitRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['format'] && !(typeof data['format'] === 'string' || data['format'] instanceof String)) {
            throw new Error("Expected the field `format` to be a primitive type in the JSON string but got " + data['format']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * @member {String} format
 */
InternalImagesHandlerUploadInitRequest.prototype['format'] = undefined;

/**
 * @member {String} name
 */
InternalImagesHandlerUploadInitRequest.prototype['name'] = undefined;






export default InternalImagesHandlerUploadInitRequest;

