export {createClient} from "./src/generated/client";
export {client} from "./src/generated/client.gen";
export * from "./src/generated/types.gen";
export * from "./src/generated/sdk.gen";

// Unified entry point
export {connect, type ConnectConfig, type AuthConfig} from "./src/connect";

// Auth surface — state machine, stores, and domain functions
export {
  isLogged,
  getToken,
  login,
  logout,
  authError,
  clearAuthError,
  requiresAction,
  limitedAccessToken,
  setLimitedAccessState,
  clearLimitedAccessState,
  user,
  initClient,
  type AuthClientConfig,
  type GoogleProviderConfig,
  type AppleProviderConfig,
  type TelegramProviderConfig,
  leaveOrganization,
  listActiveMemberships,
  listPendingMemberships,
  updateActiveMembership,
  listOrganizationMembers,
  inviteMember,
  updateMemberRole,
  deleteMember,
  MembershipRole,
  type AssignableRole,
  MembershipState,
  respondToInvitation,
  resendMemberInvite,
  publicRespondToInvitation,
  type Member,
  type Membership,
  type InviteMemberRequest,
  type UpdateMemberRoleRequest,
  type ResendInviteMemberRequest,
  updateFullName,
  updateUsername,
  verifyUserOTP,
  setupUserOTP,
  deleteUserOTP,
  getOTPStatus,
  type OTPSetup,
  type OTPStatusResponse,
  updateOrgName,
  updateOrgUsername,
  listSocials,
  connectSocial,
  disconnectSocial,
  type ConnectedProvider,
  type ProviderType,
  registerWithEmail,
  loginWithEmail,
  verifyTOTPForLogin,
  resendEmailVerificationCode,
  initiateEmailChange,
  addEmail,
  verifyEmailWithCode,
  getEmailVerificationStatus,
  sendPasswordResetEmail,
  confirmPasswordReset,
  type VerifyStatusResponse,
  type RegistrationResponse,
  type LoginOTPVerifyRequest,
  type LoginErrorResponse,
  type LoginErrorCode,
  type OAuth2ErrorResponse,
  getDomainStatus,
  initiateDomainVerification,
  checkDomainVerification,
  updateAutoJoin,
  removeDomain,
  DomainStatus,
  type DomainResponse,
  type AddDomainRequest,
  type UpdateAutoJoinRequest,
  type AutoJoinSetting,
  getBlogSubscriptionStatus,
  subscribeToBlog,
  unsubscribeFromBlog,
  type BlogSubscriptionStatus,
  beginPasskeyLogin,
  beginPasskeyRegistration,
  decodeRequestOptions,
  deletePasskey,
  finishPasskeyLogin,
  finishPasskeyRegistration,
  listPasskeys,
  renamePasskey,
  verifyPasskeyForLogin,
  type Passkey,
  type PasskeyBeginLogin,
  type PasskeyBeginRegistration,
  type PasskeyRegistrationResult,
  type TwoFactorResponse,
  type TwoFactorAuthMethod,
  type User,
  type TokenResponse,
  type LimitedScopeTokenResponse,
  type RequiresAction,
} from "./src/auth";
