/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import File from './model/File';
import FileStatus from './model/FileStatus';
import GithubComQeeqezApiInternalErrorsErrorResponse from './model/GithubComQeeqezApiInternalErrorsErrorResponse';
import Image from './model/Image';
import InternalImagesHandlerCompleteRequest from './model/InternalImagesHandlerCompleteRequest';
import InternalImagesHandlerInitResponse from './model/InternalImagesHandlerInitResponse';
import InternalImagesHandlerUploadInitRequest from './model/InternalImagesHandlerUploadInitRequest';
import PaginationPaginatedResponseImage from './model/PaginationPaginatedResponseImage';
import PaginationPagination from './model/PaginationPagination';
import ImagesApi from './api/ImagesApi';


/**
* **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don&#39;t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var RixlApi = require('index'); // See note below*.
* var xxxSvc = new RixlApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new RixlApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new RixlApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new RixlApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The File model constructor.
     * @property {module:model/File}
     */
    File,

    /**
     * The FileStatus model constructor.
     * @property {module:model/FileStatus}
     */
    FileStatus,

    /**
     * The GithubComQeeqezApiInternalErrorsErrorResponse model constructor.
     * @property {module:model/GithubComQeeqezApiInternalErrorsErrorResponse}
     */
    GithubComQeeqezApiInternalErrorsErrorResponse,

    /**
     * The Image model constructor.
     * @property {module:model/Image}
     */
    Image,

    /**
     * The InternalImagesHandlerCompleteRequest model constructor.
     * @property {module:model/InternalImagesHandlerCompleteRequest}
     */
    InternalImagesHandlerCompleteRequest,

    /**
     * The InternalImagesHandlerInitResponse model constructor.
     * @property {module:model/InternalImagesHandlerInitResponse}
     */
    InternalImagesHandlerInitResponse,

    /**
     * The InternalImagesHandlerUploadInitRequest model constructor.
     * @property {module:model/InternalImagesHandlerUploadInitRequest}
     */
    InternalImagesHandlerUploadInitRequest,

    /**
     * The PaginationPaginatedResponseImage model constructor.
     * @property {module:model/PaginationPaginatedResponseImage}
     */
    PaginationPaginatedResponseImage,

    /**
     * The PaginationPagination model constructor.
     * @property {module:model/PaginationPagination}
     */
    PaginationPagination,

    /**
    * The ImagesApi service constructor.
    * @property {module:api/ImagesApi}
    */
    ImagesApi
};
