/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ImagesUploadInitPostRequest model module.
 * @module model/ImagesUploadInitPostRequest
 * @version 2.0
 */
class ImagesUploadInitPostRequest {
    /**
     * Constructs a new <code>ImagesUploadInitPostRequest</code>.
     * @alias module:model/ImagesUploadInitPostRequest
     * @param {(module:model/InternalImagesHandlerUploadInitRequest|module:model/Object)} instance The actual instance to initialize ImagesUploadInitPostRequest.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Object
            errorMessages.push("Failed to construct Object: " + err)
        }

        // Upload initialization request
        try {
            if (typeof instance === "InternalImagesHandlerUploadInitRequest") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                InternalImagesHandlerUploadInitRequest.validateJSON(instance); // throw an exception if no match
                // create InternalImagesHandlerUploadInitRequest from JS object
                this.actualInstance = InternalImagesHandlerUploadInitRequest.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into InternalImagesHandlerUploadInitRequest
            errorMessages.push("Failed to construct InternalImagesHandlerUploadInitRequest: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `ImagesUploadInitPostRequest` with oneOf schemas InternalImagesHandlerUploadInitRequest, Object. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `ImagesUploadInitPostRequest` with oneOf schemas InternalImagesHandlerUploadInitRequest, Object. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>ImagesUploadInitPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ImagesUploadInitPostRequest} obj Optional instance to populate.
     * @return {module:model/ImagesUploadInitPostRequest} The populated <code>ImagesUploadInitPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        return new ImagesUploadInitPostRequest(data);
    }

    /**
     * Gets the actual instance, which can be <code>InternalImagesHandlerUploadInitRequest</code>, <code>Object</code>.
     * @return {(module:model/InternalImagesHandlerUploadInitRequest|module:model/Object)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>InternalImagesHandlerUploadInitRequest</code>, <code>Object</code>.
     * @param {(module:model/InternalImagesHandlerUploadInitRequest|module:model/Object)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = ImagesUploadInitPostRequest.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of ImagesUploadInitPostRequest from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/ImagesUploadInitPostRequest} An instance of ImagesUploadInitPostRequest.
     */
    static fromJSON = function(json_string){
        return ImagesUploadInitPostRequest.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} format
 */
ImagesUploadInitPostRequest.prototype['format'] = undefined;

/**
 * @member {String} name
 */
ImagesUploadInitPostRequest.prototype['name'] = undefined;


ImagesUploadInitPostRequest.OneOf = ["InternalImagesHandlerUploadInitRequest", "Object"];

export default ImagesUploadInitPostRequest;

