/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostImagesUploadInitRequest model module.
 * @module model/PostImagesUploadInitRequest
 * @version 2.0
 */
class PostImagesUploadInitRequest {
    /**
     * Constructs a new <code>PostImagesUploadInitRequest</code>.
     * @alias module:model/PostImagesUploadInitRequest
     * @param {(module:model/InternalImagesHandlerUploadInitRequest|module:model/Object)} instance The actual instance to initialize PostImagesUploadInitRequest.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Object
            errorMessages.push("Failed to construct Object: " + err)
        }

        // Upload initialization request
        try {
            if (typeof instance === "InternalImagesHandlerUploadInitRequest") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                InternalImagesHandlerUploadInitRequest.validateJSON(instance); // throw an exception if no match
                // create InternalImagesHandlerUploadInitRequest from JS object
                this.actualInstance = InternalImagesHandlerUploadInitRequest.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into InternalImagesHandlerUploadInitRequest
            errorMessages.push("Failed to construct InternalImagesHandlerUploadInitRequest: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `PostImagesUploadInitRequest` with oneOf schemas InternalImagesHandlerUploadInitRequest, Object. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `PostImagesUploadInitRequest` with oneOf schemas InternalImagesHandlerUploadInitRequest, Object. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>PostImagesUploadInitRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostImagesUploadInitRequest} obj Optional instance to populate.
     * @return {module:model/PostImagesUploadInitRequest} The populated <code>PostImagesUploadInitRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        return new PostImagesUploadInitRequest(data);
    }

    /**
     * Gets the actual instance, which can be <code>InternalImagesHandlerUploadInitRequest</code>, <code>Object</code>.
     * @return {(module:model/InternalImagesHandlerUploadInitRequest|module:model/Object)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>InternalImagesHandlerUploadInitRequest</code>, <code>Object</code>.
     * @param {(module:model/InternalImagesHandlerUploadInitRequest|module:model/Object)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = PostImagesUploadInitRequest.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of PostImagesUploadInitRequest from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/PostImagesUploadInitRequest} An instance of PostImagesUploadInitRequest.
     */
    static fromJSON = function(json_string){
        return PostImagesUploadInitRequest.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} format
 */
PostImagesUploadInitRequest.prototype['format'] = undefined;

/**
 * @member {String} name
 */
PostImagesUploadInitRequest.prototype['name'] = undefined;


PostImagesUploadInitRequest.OneOf = ["InternalImagesHandlerUploadInitRequest", "Object"];

export default PostImagesUploadInitRequest;

