/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostImagesUploadCompleteRequest model module.
 * @module model/PostImagesUploadCompleteRequest
 * @version 2.0
 */
class PostImagesUploadCompleteRequest {
    /**
     * Constructs a new <code>PostImagesUploadCompleteRequest</code>.
     * @alias module:model/PostImagesUploadCompleteRequest
     * @param {(module:model/InternalImagesHandlerCompleteRequest|module:model/Object)} instance The actual instance to initialize PostImagesUploadCompleteRequest.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Object
            errorMessages.push("Failed to construct Object: " + err)
        }

        // Upload completion request
        try {
            if (typeof instance === "InternalImagesHandlerCompleteRequest") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                InternalImagesHandlerCompleteRequest.validateJSON(instance); // throw an exception if no match
                // create InternalImagesHandlerCompleteRequest from JS object
                this.actualInstance = InternalImagesHandlerCompleteRequest.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into InternalImagesHandlerCompleteRequest
            errorMessages.push("Failed to construct InternalImagesHandlerCompleteRequest: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `PostImagesUploadCompleteRequest` with oneOf schemas InternalImagesHandlerCompleteRequest, Object. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `PostImagesUploadCompleteRequest` with oneOf schemas InternalImagesHandlerCompleteRequest, Object. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>PostImagesUploadCompleteRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostImagesUploadCompleteRequest} obj Optional instance to populate.
     * @return {module:model/PostImagesUploadCompleteRequest} The populated <code>PostImagesUploadCompleteRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        return new PostImagesUploadCompleteRequest(data);
    }

    /**
     * Gets the actual instance, which can be <code>InternalImagesHandlerCompleteRequest</code>, <code>Object</code>.
     * @return {(module:model/InternalImagesHandlerCompleteRequest|module:model/Object)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>InternalImagesHandlerCompleteRequest</code>, <code>Object</code>.
     * @param {(module:model/InternalImagesHandlerCompleteRequest|module:model/Object)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = PostImagesUploadCompleteRequest.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of PostImagesUploadCompleteRequest from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/PostImagesUploadCompleteRequest} An instance of PostImagesUploadCompleteRequest.
     */
    static fromJSON = function(json_string){
        return PostImagesUploadCompleteRequest.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {Boolean} attached_to_video
 */
PostImagesUploadCompleteRequest.prototype['attached_to_video'] = undefined;

/**
 * @member {String} image_id
 */
PostImagesUploadCompleteRequest.prototype['image_id'] = undefined;


PostImagesUploadCompleteRequest.OneOf = ["InternalImagesHandlerCompleteRequest", "Object"];

export default PostImagesUploadCompleteRequest;

