/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RixlApi);
  }
}(this, function(expect, RixlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RixlApi.VideosApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VideosApi', function() {
    describe('deleteVideosVideoIdAudioTracks', function() {
      it('should call deleteVideosVideoIdAudioTracks successfully', function(done) {
        //uncomment below and update the code to test deleteVideosVideoIdAudioTracks
        //instance.deleteVideosVideoIdAudioTracks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVideosVideoIdAudioTracksLangCode', function() {
      it('should call deleteVideosVideoIdAudioTracksLangCode successfully', function(done) {
        //uncomment below and update the code to test deleteVideosVideoIdAudioTracksLangCode
        //instance.deleteVideosVideoIdAudioTracksLangCode(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVideosVideoIdAudioTracksTrackId', function() {
      it('should call deleteVideosVideoIdAudioTracksTrackId successfully', function(done) {
        //uncomment below and update the code to test deleteVideosVideoIdAudioTracksTrackId
        //instance.deleteVideosVideoIdAudioTracksTrackId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVideosVideoIdChapters', function() {
      it('should call deleteVideosVideoIdChapters successfully', function(done) {
        //uncomment below and update the code to test deleteVideosVideoIdChapters
        //instance.deleteVideosVideoIdChapters(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVideosVideoIdDelete', function() {
      it('should call deleteVideosVideoIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteVideosVideoIdDelete
        //instance.deleteVideosVideoIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVideosVideoIdSubtitles', function() {
      it('should call deleteVideosVideoIdSubtitles successfully', function(done) {
        //uncomment below and update the code to test deleteVideosVideoIdSubtitles
        //instance.deleteVideosVideoIdSubtitles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVideosVideoIdSubtitlesLangCode', function() {
      it('should call deleteVideosVideoIdSubtitlesLangCode successfully', function(done) {
        //uncomment below and update the code to test deleteVideosVideoIdSubtitlesLangCode
        //instance.deleteVideosVideoIdSubtitlesLangCode(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVideosVideoIdSubtitlesSubtitleId', function() {
      it('should call deleteVideosVideoIdSubtitlesSubtitleId successfully', function(done) {
        //uncomment below and update the code to test deleteVideosVideoIdSubtitlesSubtitleId
        //instance.deleteVideosVideoIdSubtitlesSubtitleId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVideos', function() {
      it('should call getVideos successfully', function(done) {
        //uncomment below and update the code to test getVideos
        //instance.getVideos(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVideosLanguages', function() {
      it('should call getVideosLanguages successfully', function(done) {
        //uncomment below and update the code to test getVideosLanguages
        //instance.getVideosLanguages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVideosVideoId', function() {
      it('should call getVideosVideoId successfully', function(done) {
        //uncomment below and update the code to test getVideosVideoId
        //instance.getVideosVideoId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postVideosUploadComplete', function() {
      it('should call postVideosUploadComplete successfully', function(done) {
        //uncomment below and update the code to test postVideosUploadComplete
        //instance.postVideosUploadComplete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postVideosUploadInit', function() {
      it('should call postVideosUploadInit successfully', function(done) {
        //uncomment below and update the code to test postVideosUploadInit
        //instance.postVideosUploadInit(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postVideosVideoIdAudioTracks', function() {
      it('should call postVideosVideoIdAudioTracks successfully', function(done) {
        //uncomment below and update the code to test postVideosVideoIdAudioTracks
        //instance.postVideosVideoIdAudioTracks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postVideosVideoIdSubtitles', function() {
      it('should call postVideosVideoIdSubtitles successfully', function(done) {
        //uncomment below and update the code to test postVideosVideoIdSubtitles
        //instance.postVideosVideoIdSubtitles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putVideosVideoIdAudioTracksLangCode', function() {
      it('should call putVideosVideoIdAudioTracksLangCode successfully', function(done) {
        //uncomment below and update the code to test putVideosVideoIdAudioTracksLangCode
        //instance.putVideosVideoIdAudioTracksLangCode(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putVideosVideoIdChapters', function() {
      it('should call putVideosVideoIdChapters successfully', function(done) {
        //uncomment below and update the code to test putVideosVideoIdChapters
        //instance.putVideosVideoIdChapters(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putVideosVideoIdSubtitlesLangCode', function() {
      it('should call putVideosVideoIdSubtitlesLangCode successfully', function(done) {
        //uncomment below and update the code to test putVideosVideoIdSubtitlesLangCode
        //instance.putVideosVideoIdSubtitlesLangCode(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putVideosVideoIdThumbnail', function() {
      it('should call putVideosVideoIdThumbnail successfully', function(done) {
        //uncomment below and update the code to test putVideosVideoIdThumbnail
        //instance.putVideosVideoIdThumbnail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
