/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GithubComQeeqezApiInternalErrorsErrorResponse from '../models/GithubComQeeqezApiInternalErrorsErrorResponse';
import PaginationPaginatedResponsePost from '../models/PaginationPaginatedResponsePost';
import Post from '../models/Post';

/**
* Feeds service.
* @module services/FeedsApi
* @version 2.0.0
*/
export default class FeedsApi {

    /**
    * Constructs a new FeedsApi. 
    * @alias module:services/FeedsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * List posts in a feed
     * Retrieve posts in a feed, with pagination.
     * @param {String} feedId Feed ID
     * @param {Object} opts Optional parameters
     * @param {Number} [limit = 25)] Maximum number of items to return in a single request. <br> **Default:** `25`
     * @param {Number} [offset = 0)] Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/PaginationPaginatedResponsePost} and HTTP response
     */
    getFeedsFeedIdWithHttpInfo(feedId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'feedId' is set
      if (feedId === undefined || feedId === null) {
        throw new Error("Missing the required parameter 'feedId' when calling getFeedsFeedId");
      }

      let pathParams = {
        'feedId': feedId
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginationPaginatedResponsePost;
      return this.apiClient.callApi(
        '/feeds/{feedId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List posts in a feed
     * Retrieve posts in a feed, with pagination.
     * @param {String} feedId Feed ID
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Maximum number of items to return in a single request. <br> **Default:** `25` (default to 25)
     * @param {Number} opts.offset Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0` (default to 0)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/PaginationPaginatedResponsePost}
     */
    getFeedsFeedId(feedId, opts) {
      return this.getFeedsFeedIdWithHttpInfo(feedId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List posts by creator
     * Retrieve posts in a feed by a specific creator, with pagination.
     * @param {String} feedId Feed ID
     * @param {String} creatorId Creator ID
     * @param {Object} opts Optional parameters
     * @param {Number} [limit = 25)] Maximum number of items to return in a single request. <br> **Default:** `25`
     * @param {Number} [offset = 0)] Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/PaginationPaginatedResponsePost} and HTTP response
     */
    getFeedsFeedIdCreatorsCreatorIdWithHttpInfo(feedId, creatorId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'feedId' is set
      if (feedId === undefined || feedId === null) {
        throw new Error("Missing the required parameter 'feedId' when calling getFeedsFeedIdCreatorsCreatorId");
      }
      // verify the required parameter 'creatorId' is set
      if (creatorId === undefined || creatorId === null) {
        throw new Error("Missing the required parameter 'creatorId' when calling getFeedsFeedIdCreatorsCreatorId");
      }

      let pathParams = {
        'feedId': feedId,
        'creatorId': creatorId
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginationPaginatedResponsePost;
      return this.apiClient.callApi(
        '/feeds/{feedId}/creators/{creatorId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List posts by creator
     * Retrieve posts in a feed by a specific creator, with pagination.
     * @param {String} feedId Feed ID
     * @param {String} creatorId Creator ID
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Maximum number of items to return in a single request. <br> **Default:** `25` (default to 25)
     * @param {Number} opts.offset Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0` (default to 0)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/PaginationPaginatedResponsePost}
     */
    getFeedsFeedIdCreatorsCreatorId(feedId, creatorId, opts) {
      return this.getFeedsFeedIdCreatorsCreatorIdWithHttpInfo(feedId, creatorId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a post
     * Retrieve a post from feed by its ID
     * @param {String} feedId Feed ID
     * @param {String} postId Post ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/Post} and HTTP response
     */
    getFeedsFeedIdPostIdWithHttpInfo(feedId, postId) {
      let postBody = null;
      // verify the required parameter 'feedId' is set
      if (feedId === undefined || feedId === null) {
        throw new Error("Missing the required parameter 'feedId' when calling getFeedsFeedIdPostId");
      }
      // verify the required parameter 'postId' is set
      if (postId === undefined || postId === null) {
        throw new Error("Missing the required parameter 'postId' when calling getFeedsFeedIdPostId");
      }

      let pathParams = {
        'feedId': feedId,
        'postId': postId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Post;
      return this.apiClient.callApi(
        '/feeds/{feedId}/{postId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get a post
     * Retrieve a post from feed by its ID
     * @param {String} feedId Feed ID
     * @param {String} postId Post ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/Post}
     */
    getFeedsFeedIdPostId(feedId, postId) {
      return this.getFeedsFeedIdPostIdWithHttpInfo(feedId, postId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
