/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaginationPagination model module.
 * @module model/PaginationPagination
 * @version 2.0
 */
class PaginationPagination {
    /**
     * Constructs a new <code>PaginationPagination</code>.
     * Pagination data for the request.
     * @alias module:model/PaginationPagination
     */
    constructor() { 
        
        PaginationPagination.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['limit'] = 25;
        obj['offset'] = 0;
    }

    /**
     * Constructs a <code>PaginationPagination</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaginationPagination} obj Optional instance to populate.
     * @return {module:model/PaginationPagination} The populated <code>PaginationPagination</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginationPagination();

            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaginationPagination</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaginationPagination</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Maximum number of items to return in a single request.
 * @member {Number} limit
 * @default 25
 */
PaginationPagination.prototype['limit'] = 25;

/**
 * Starting point of the result set.
 * @member {Number} offset
 * @default 0
 */
PaginationPagination.prototype['offset'] = 0;

/**
 * The total number of available items in the full list.
 * @member {Number} total
 */
PaginationPagination.prototype['total'] = undefined;






export default PaginationPagination;

