/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GithubComQeeqezApiInternalVideosTypesChapterInput from './GithubComQeeqezApiInternalVideosTypesChapterInput';

/**
 * The PutVideosVideoIdChaptersRequest model module.
 * @module model/PutVideosVideoIdChaptersRequest
 * @version 2.0
 */
class PutVideosVideoIdChaptersRequest {
    /**
     * Constructs a new <code>PutVideosVideoIdChaptersRequest</code>.
     * @alias module:model/PutVideosVideoIdChaptersRequest
     * @param {(module:model/Object|module:model/UpdateChaptersRequest)} instance The actual instance to initialize PutVideosVideoIdChaptersRequest.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Object
            errorMessages.push("Failed to construct Object: " + err)
        }

        // Chapters array
        try {
            if (typeof instance === "UpdateChaptersRequest") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                UpdateChaptersRequest.validateJSON(instance); // throw an exception if no match
                // create UpdateChaptersRequest from JS object
                this.actualInstance = UpdateChaptersRequest.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into UpdateChaptersRequest
            errorMessages.push("Failed to construct UpdateChaptersRequest: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `PutVideosVideoIdChaptersRequest` with oneOf schemas Object, UpdateChaptersRequest. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `PutVideosVideoIdChaptersRequest` with oneOf schemas Object, UpdateChaptersRequest. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>PutVideosVideoIdChaptersRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PutVideosVideoIdChaptersRequest} obj Optional instance to populate.
     * @return {module:model/PutVideosVideoIdChaptersRequest} The populated <code>PutVideosVideoIdChaptersRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        return new PutVideosVideoIdChaptersRequest(data);
    }

    /**
     * Gets the actual instance, which can be <code>Object</code>, <code>UpdateChaptersRequest</code>.
     * @return {(module:model/Object|module:model/UpdateChaptersRequest)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>Object</code>, <code>UpdateChaptersRequest</code>.
     * @param {(module:model/Object|module:model/UpdateChaptersRequest)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = PutVideosVideoIdChaptersRequest.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of PutVideosVideoIdChaptersRequest from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/PutVideosVideoIdChaptersRequest} An instance of PutVideosVideoIdChaptersRequest.
     */
    static fromJSON = function(json_string){
        return PutVideosVideoIdChaptersRequest.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {Array.<module:model/GithubComQeeqezApiInternalVideosTypesChapterInput>} chapters
 */
PutVideosVideoIdChaptersRequest.prototype['chapters'] = undefined;


PutVideosVideoIdChaptersRequest.OneOf = ["Object", "UpdateChaptersRequest"];

export default PutVideosVideoIdChaptersRequest;

