/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GithubComQeeqezApiDbSqlcVideoQuality from './GithubComQeeqezApiDbSqlcVideoQuality';

/**
 * The VideoUploadInitRequest model module.
 * @module model/VideoUploadInitRequest
 * @version 2.0
 */
class VideoUploadInitRequest {
    /**
     * Constructs a new <code>VideoUploadInitRequest</code>.
     * @alias module:model/VideoUploadInitRequest
     * @param fileName {String} 
     */
    constructor(fileName) { 
        
        VideoUploadInitRequest.initialize(this, fileName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fileName) { 
        obj['file_name'] = fileName;
    }

    /**
     * Constructs a <code>VideoUploadInitRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VideoUploadInitRequest} obj Optional instance to populate.
     * @return {module:model/VideoUploadInitRequest} The populated <code>VideoUploadInitRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VideoUploadInitRequest();

            if (data.hasOwnProperty('file_name')) {
                obj['file_name'] = ApiClient.convertToType(data['file_name'], 'String');
            }
            if (data.hasOwnProperty('image_format')) {
                obj['image_format'] = ApiClient.convertToType(data['image_format'], 'String');
            }
            if (data.hasOwnProperty('video_quality')) {
                obj['video_quality'] = ApiClient.convertToType(data['video_quality'], GithubComQeeqezApiDbSqlcVideoQuality);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VideoUploadInitRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VideoUploadInitRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of VideoUploadInitRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['file_name'] && !(typeof data['file_name'] === 'string' || data['file_name'] instanceof String)) {
            throw new Error("Expected the field `file_name` to be a primitive type in the JSON string but got " + data['file_name']);
        }
        // ensure the json data is a string
        if (data['image_format'] && !(typeof data['image_format'] === 'string' || data['image_format'] instanceof String)) {
            throw new Error("Expected the field `image_format` to be a primitive type in the JSON string but got " + data['image_format']);
        }

        return true;
    }


}

VideoUploadInitRequest.RequiredProperties = ["file_name"];

/**
 * @member {String} file_name
 */
VideoUploadInitRequest.prototype['file_name'] = undefined;

/**
 * @member {String} image_format
 */
VideoUploadInitRequest.prototype['image_format'] = undefined;

/**
 * @member {module:model/GithubComQeeqezApiDbSqlcVideoQuality} video_quality
 */
VideoUploadInitRequest.prototype['video_quality'] = undefined;






export default VideoUploadInitRequest;

