/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GithubComQeeqezApiDbSqlcVideoQuality from './GithubComQeeqezApiDbSqlcVideoQuality';

/**
 * The VideosUploadInitPostRequest model module.
 * @module model/VideosUploadInitPostRequest
 * @version 2.0
 */
class VideosUploadInitPostRequest {
    /**
     * Constructs a new <code>VideosUploadInitPostRequest</code>.
     * @alias module:model/VideosUploadInitPostRequest
     * @param {(module:model/Object|module:model/VideoUploadInitRequest)} instance The actual instance to initialize VideosUploadInitPostRequest.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Object
            errorMessages.push("Failed to construct Object: " + err)
        }

        // Video upload initialization request
        try {
            if (typeof instance === "VideoUploadInitRequest") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                VideoUploadInitRequest.validateJSON(instance); // throw an exception if no match
                // create VideoUploadInitRequest from JS object
                this.actualInstance = VideoUploadInitRequest.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into VideoUploadInitRequest
            errorMessages.push("Failed to construct VideoUploadInitRequest: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `VideosUploadInitPostRequest` with oneOf schemas Object, VideoUploadInitRequest. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `VideosUploadInitPostRequest` with oneOf schemas Object, VideoUploadInitRequest. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>VideosUploadInitPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VideosUploadInitPostRequest} obj Optional instance to populate.
     * @return {module:model/VideosUploadInitPostRequest} The populated <code>VideosUploadInitPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        return new VideosUploadInitPostRequest(data);
    }

    /**
     * Gets the actual instance, which can be <code>Object</code>, <code>VideoUploadInitRequest</code>.
     * @return {(module:model/Object|module:model/VideoUploadInitRequest)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>Object</code>, <code>VideoUploadInitRequest</code>.
     * @param {(module:model/Object|module:model/VideoUploadInitRequest)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = VideosUploadInitPostRequest.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of VideosUploadInitPostRequest from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/VideosUploadInitPostRequest} An instance of VideosUploadInitPostRequest.
     */
    static fromJSON = function(json_string){
        return VideosUploadInitPostRequest.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} file_name
 */
VideosUploadInitPostRequest.prototype['file_name'] = undefined;

/**
 * @member {String} image_format
 */
VideosUploadInitPostRequest.prototype['image_format'] = undefined;

/**
 * @member {module:model/GithubComQeeqezApiDbSqlcVideoQuality} video_quality
 */
VideosUploadInitPostRequest.prototype['video_quality'] = undefined;


VideosUploadInitPostRequest.OneOf = ["Object", "VideoUploadInitRequest"];

export default VideosUploadInitPostRequest;

