/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RixlApi);
  }
}(this, function(expect, RixlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RixlApi.PostVideosUploadInitRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostVideosUploadInitRequest', function() {
    it('should create an instance of PostVideosUploadInitRequest', function() {
      // uncomment below and update the code to test PostVideosUploadInitRequest
      //var instance = new RixlApi.PostVideosUploadInitRequest();
      //expect(instance).to.be.a(RixlApi.PostVideosUploadInitRequest);
    });

    it('should have the property fileName (base name: "file_name")', function() {
      // uncomment below and update the code to test the property fileName
      //var instance = new RixlApi.PostVideosUploadInitRequest();
      //expect(instance).to.be();
    });

    it('should have the property imageFormat (base name: "image_format")', function() {
      // uncomment below and update the code to test the property imageFormat
      //var instance = new RixlApi.PostVideosUploadInitRequest();
      //expect(instance).to.be();
    });

    it('should have the property videoQuality (base name: "video_quality")', function() {
      // uncomment below and update the code to test the property videoQuality
      //var instance = new RixlApi.PostVideosUploadInitRequest();
      //expect(instance).to.be();
    });

  });

}));
