/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RixlApi);
  }
}(this, function(expect, RixlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RixlApi.Video();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Video', function() {
    it('should create an instance of Video', function() {
      // uncomment below and update the code to test Video
      //var instance = new RixlApi.Video();
      //expect(instance).to.be.a(RixlApi.Video);
    });

    it('should have the property bitrate (base name: "bitrate")', function() {
      // uncomment below and update the code to test the property bitrate
      //var instance = new RixlApi.Video();
      //expect(instance).to.be();
    });

    it('should have the property chapters (base name: "chapters")', function() {
      // uncomment below and update the code to test the property chapters
      //var instance = new RixlApi.Video();
      //expect(instance).to.be();
    });

    it('should have the property codec (base name: "codec")', function() {
      // uncomment below and update the code to test the property codec
      //var instance = new RixlApi.Video();
      //expect(instance).to.be();
    });

    it('should have the property duration (base name: "duration")', function() {
      // uncomment below and update the code to test the property duration
      //var instance = new RixlApi.Video();
      //expect(instance).to.be();
    });

    it('should have the property file (base name: "file")', function() {
      // uncomment below and update the code to test the property file
      //var instance = new RixlApi.Video();
      //expect(instance).to.be();
    });

    it('should have the property framerate (base name: "framerate")', function() {
      // uncomment below and update the code to test the property framerate
      //var instance = new RixlApi.Video();
      //expect(instance).to.be();
    });

    it('should have the property hdr (base name: "hdr")', function() {
      // uncomment below and update the code to test the property hdr
      //var instance = new RixlApi.Video();
      //expect(instance).to.be();
    });

    it('should have the property height (base name: "height")', function() {
      // uncomment below and update the code to test the property height
      //var instance = new RixlApi.Video();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new RixlApi.Video();
      //expect(instance).to.be();
    });

    it('should have the property planType (base name: "plan_type")', function() {
      // uncomment below and update the code to test the property planType
      //var instance = new RixlApi.Video();
      //expect(instance).to.be();
    });

    it('should have the property poster (base name: "poster")', function() {
      // uncomment below and update the code to test the property poster
      //var instance = new RixlApi.Video();
      //expect(instance).to.be();
    });

    it('should have the property width (base name: "width")', function() {
      // uncomment below and update the code to test the property width
      //var instance = new RixlApi.Video();
      //expect(instance).to.be();
    });

  });

}));
