/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AudioTrack from '../model/AudioTrack';
import AudioTrackDelete from '../model/AudioTrackDelete';
import GithubComQeeqezApiInternalErrorsErrorResponse from '../model/GithubComQeeqezApiInternalErrorsErrorResponse';
import GithubComQeeqezApiInternalVideosHandlerUploadInitResponse from '../model/GithubComQeeqezApiInternalVideosHandlerUploadInitResponse';
import InternalVideosHandlerSubtitlesLanguageResponse from '../model/InternalVideosHandlerSubtitlesLanguageResponse';
import PaginationPaginatedResponseVideo from '../model/PaginationPaginatedResponseVideo';
import PostVideosUploadCompleteRequest from '../model/PostVideosUploadCompleteRequest';
import PostVideosUploadInitRequest from '../model/PostVideosUploadInitRequest';
import PutVideosVideoIdChaptersRequest from '../model/PutVideosVideoIdChaptersRequest';
import Subtitle from '../model/Subtitle';
import SubtitleDelete from '../model/SubtitleDelete';
import UpdateChaptersResponse from '../model/UpdateChaptersResponse';
import Video from '../model/Video';

/**
* Videos service.
* @module api/VideosApi
* @version 2.0
*/
export default class VideosApi {

    /**
    * Constructs a new VideosApi. 
    * @alias module:api/VideosApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Delete all audio tracks
     * Remove all additional audio tracks from a video using API key authentication
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AudioTrackDelete} and HTTP response
     */
    deleteVideosVideoIdAudioTracksWithHttpInfo(videoId) {
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling deleteVideosVideoIdAudioTracks");
      }

      let pathParams = {
        'videoId': videoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AudioTrackDelete;
      return this.apiClient.callApi(
        '/videos/{videoId}/audio-tracks', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete all audio tracks
     * Remove all additional audio tracks from a video using API key authentication
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AudioTrackDelete}
     */
    deleteVideosVideoIdAudioTracks(videoId) {
      return this.deleteVideosVideoIdAudioTracksWithHttpInfo(videoId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete audio track by language
     * Remove an audio track for a specific language using API key authentication
     * @param {String} videoId Video ID
     * @param {String} langCode Language Code (BCP 47)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AudioTrackDelete} and HTTP response
     */
    deleteVideosVideoIdAudioTracksLangCodeWithHttpInfo(videoId, langCode) {
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling deleteVideosVideoIdAudioTracksLangCode");
      }
      // verify the required parameter 'langCode' is set
      if (langCode === undefined || langCode === null) {
        throw new Error("Missing the required parameter 'langCode' when calling deleteVideosVideoIdAudioTracksLangCode");
      }

      let pathParams = {
        'videoId': videoId,
        'lang_code': langCode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AudioTrackDelete;
      return this.apiClient.callApi(
        '/videos/{videoId}/audio-tracks/{lang_code}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete audio track by language
     * Remove an audio track for a specific language using API key authentication
     * @param {String} videoId Video ID
     * @param {String} langCode Language Code (BCP 47)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AudioTrackDelete}
     */
    deleteVideosVideoIdAudioTracksLangCode(videoId, langCode) {
      return this.deleteVideosVideoIdAudioTracksLangCodeWithHttpInfo(videoId, langCode)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete audio track
     * Remove an additional audio track from a video using API key authentication
     * @param {String} videoId Video ID
     * @param {String} trackId Audio Track ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AudioTrackDelete} and HTTP response
     */
    deleteVideosVideoIdAudioTracksTrackIdWithHttpInfo(videoId, trackId) {
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling deleteVideosVideoIdAudioTracksTrackId");
      }
      // verify the required parameter 'trackId' is set
      if (trackId === undefined || trackId === null) {
        throw new Error("Missing the required parameter 'trackId' when calling deleteVideosVideoIdAudioTracksTrackId");
      }

      let pathParams = {
        'videoId': videoId,
        'trackId': trackId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AudioTrackDelete;
      return this.apiClient.callApi(
        '/videos/{videoId}/audio-tracks/{trackId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete audio track
     * Remove an additional audio track from a video using API key authentication
     * @param {String} videoId Video ID
     * @param {String} trackId Audio Track ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AudioTrackDelete}
     */
    deleteVideosVideoIdAudioTracksTrackId(videoId, trackId) {
      return this.deleteVideosVideoIdAudioTracksTrackIdWithHttpInfo(videoId, trackId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete video chapters
     * Remove all chapters from a video using API key authentication
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UpdateChaptersResponse} and HTTP response
     */
    deleteVideosVideoIdChaptersWithHttpInfo(videoId) {
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling deleteVideosVideoIdChapters");
      }

      let pathParams = {
        'videoId': videoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UpdateChaptersResponse;
      return this.apiClient.callApi(
        '/videos/{videoId}/chapters', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete video chapters
     * Remove all chapters from a video using API key authentication
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UpdateChaptersResponse}
     */
    deleteVideosVideoIdChapters(videoId) {
      return this.deleteVideosVideoIdChaptersWithHttpInfo(videoId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete video
     * Delete a video by its ID within a project
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteVideosVideoIdDeleteWithHttpInfo(videoId) {
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling deleteVideosVideoIdDelete");
      }

      let pathParams = {
        'videoId': videoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/videos/{videoId}/delete', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete video
     * Delete a video by its ID within a project
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteVideosVideoIdDelete(videoId) {
      return this.deleteVideosVideoIdDeleteWithHttpInfo(videoId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete all subtitles
     * Remove all subtitles from a video using API key authentication
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SubtitleDelete} and HTTP response
     */
    deleteVideosVideoIdSubtitlesWithHttpInfo(videoId) {
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling deleteVideosVideoIdSubtitles");
      }

      let pathParams = {
        'videoId': videoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SubtitleDelete;
      return this.apiClient.callApi(
        '/videos/{videoId}/subtitles', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete all subtitles
     * Remove all subtitles from a video using API key authentication
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SubtitleDelete}
     */
    deleteVideosVideoIdSubtitles(videoId) {
      return this.deleteVideosVideoIdSubtitlesWithHttpInfo(videoId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete subtitle by language
     * Remove a subtitle for a specific language using API key authentication
     * @param {String} videoId Video ID
     * @param {String} langCode Language Code (BCP 47)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SubtitleDelete} and HTTP response
     */
    deleteVideosVideoIdSubtitlesLangCodeWithHttpInfo(videoId, langCode) {
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling deleteVideosVideoIdSubtitlesLangCode");
      }
      // verify the required parameter 'langCode' is set
      if (langCode === undefined || langCode === null) {
        throw new Error("Missing the required parameter 'langCode' when calling deleteVideosVideoIdSubtitlesLangCode");
      }

      let pathParams = {
        'videoId': videoId,
        'lang_code': langCode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SubtitleDelete;
      return this.apiClient.callApi(
        '/videos/{videoId}/subtitles/{lang_code}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete subtitle by language
     * Remove a subtitle for a specific language using API key authentication
     * @param {String} videoId Video ID
     * @param {String} langCode Language Code (BCP 47)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SubtitleDelete}
     */
    deleteVideosVideoIdSubtitlesLangCode(videoId, langCode) {
      return this.deleteVideosVideoIdSubtitlesLangCodeWithHttpInfo(videoId, langCode)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete subtitle
     * Remove a subtitle from a video using API key authentication
     * @param {String} videoId Video ID
     * @param {String} subtitleId Subtitle ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SubtitleDelete} and HTTP response
     */
    deleteVideosVideoIdSubtitlesSubtitleIdWithHttpInfo(videoId, subtitleId) {
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling deleteVideosVideoIdSubtitlesSubtitleId");
      }
      // verify the required parameter 'subtitleId' is set
      if (subtitleId === undefined || subtitleId === null) {
        throw new Error("Missing the required parameter 'subtitleId' when calling deleteVideosVideoIdSubtitlesSubtitleId");
      }

      let pathParams = {
        'videoId': videoId,
        'subtitleId': subtitleId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SubtitleDelete;
      return this.apiClient.callApi(
        '/videos/{videoId}/subtitles/{subtitleId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete subtitle
     * Remove a subtitle from a video using API key authentication
     * @param {String} videoId Video ID
     * @param {String} subtitleId Subtitle ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SubtitleDelete}
     */
    deleteVideosVideoIdSubtitlesSubtitleId(videoId, subtitleId) {
      return this.deleteVideosVideoIdSubtitlesSubtitleIdWithHttpInfo(videoId, subtitleId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List videos for a project
     * Retrieve all videos for a specific project, with pagination and sorting.
     * @param {Object} opts Optional parameters
     * @param {Number} [limit = 25)] Maximum number of items to return in a single request. <br> **Default:** `25`
     * @param {Number} [offset = 0)] Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
     * @param {String} [sort] Field to sort by (created_at, name, size, updated_at, duration)
     * @param {String} [order] Sort order (asc, desc)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginationPaginatedResponseVideo} and HTTP response
     */
    getVideosWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset'],
        'sort': opts['sort'],
        'order': opts['order']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginationPaginatedResponseVideo;
      return this.apiClient.callApi(
        '/videos', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List videos for a project
     * Retrieve all videos for a specific project, with pagination and sorting.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Maximum number of items to return in a single request. <br> **Default:** `25` (default to 25)
     * @param {Number} opts.offset Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0` (default to 0)
     * @param {String} opts.sort Field to sort by (created_at, name, size, updated_at, duration)
     * @param {String} opts.order Sort order (asc, desc)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginationPaginatedResponseVideo}
     */
    getVideos(opts) {
      return this.getVideosWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List available subtitle languages
     * Get list of supported languages for subtitles
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/InternalVideosHandlerSubtitlesLanguageResponse>} and HTTP response
     */
    getVideosLanguagesWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [InternalVideosHandlerSubtitlesLanguageResponse];
      return this.apiClient.callApi(
        '/videos/languages', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List available subtitle languages
     * Get list of supported languages for subtitles
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/InternalVideosHandlerSubtitlesLanguageResponse>}
     */
    getVideosLanguages() {
      return this.getVideosLanguagesWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a video
     * Retrieve a video by its ID for a specific project.
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Video} and HTTP response
     */
    getVideosVideoIdWithHttpInfo(videoId) {
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling getVideosVideoId");
      }

      let pathParams = {
        'videoId': videoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Video;
      return this.apiClient.callApi(
        '/videos/{videoId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get a video
     * Retrieve a video by its ID for a specific project.
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Video}
     */
    getVideosVideoId(videoId) {
      return this.getVideosVideoIdWithHttpInfo(videoId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Upload: Mark as complete
     * Mark a video upload as complete after successful upload to storage using API key authentication
     * @param {module:model/PostVideosUploadCompleteRequest} postVideosUploadCompleteRequest Video upload completion request
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Video} and HTTP response
     */
    postVideosUploadCompleteWithHttpInfo(postVideosUploadCompleteRequest) {
      let postBody = postVideosUploadCompleteRequest;
      // verify the required parameter 'postVideosUploadCompleteRequest' is set
      if (postVideosUploadCompleteRequest === undefined || postVideosUploadCompleteRequest === null) {
        throw new Error("Missing the required parameter 'postVideosUploadCompleteRequest' when calling postVideosUploadComplete");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Video;
      return this.apiClient.callApi(
        '/videos/upload/complete', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Upload: Mark as complete
     * Mark a video upload as complete after successful upload to storage using API key authentication
     * @param {module:model/PostVideosUploadCompleteRequest} postVideosUploadCompleteRequest Video upload completion request
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Video}
     */
    postVideosUploadComplete(postVideosUploadCompleteRequest) {
      return this.postVideosUploadCompleteWithHttpInfo(postVideosUploadCompleteRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Upload: Init
     * Initialize a video upload and get presigned URLs for video and poster using API key authentication
     * @param {module:model/PostVideosUploadInitRequest} postVideosUploadInitRequest Video upload initialization request
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GithubComQeeqezApiInternalVideosHandlerUploadInitResponse} and HTTP response
     */
    postVideosUploadInitWithHttpInfo(postVideosUploadInitRequest) {
      let postBody = postVideosUploadInitRequest;
      // verify the required parameter 'postVideosUploadInitRequest' is set
      if (postVideosUploadInitRequest === undefined || postVideosUploadInitRequest === null) {
        throw new Error("Missing the required parameter 'postVideosUploadInitRequest' when calling postVideosUploadInit");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GithubComQeeqezApiInternalVideosHandlerUploadInitResponse;
      return this.apiClient.callApi(
        '/videos/upload/init', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Upload: Init
     * Initialize a video upload and get presigned URLs for video and poster using API key authentication
     * @param {module:model/PostVideosUploadInitRequest} postVideosUploadInitRequest Video upload initialization request
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GithubComQeeqezApiInternalVideosHandlerUploadInitResponse}
     */
    postVideosUploadInit(postVideosUploadInitRequest) {
      return this.postVideosUploadInitWithHttpInfo(postVideosUploadInitRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Bulk upsert video audio tracks
     * Replace all audio tracks with the provided ones using API key authentication
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/AudioTrack>} and HTTP response
     */
    postVideosVideoIdAudioTracksWithHttpInfo(videoId) {
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling postVideosVideoIdAudioTracks");
      }

      let pathParams = {
        'videoId': videoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = [AudioTrack];
      return this.apiClient.callApi(
        '/videos/{videoId}/audio-tracks', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Bulk upsert video audio tracks
     * Replace all audio tracks with the provided ones using API key authentication
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/AudioTrack>}
     */
    postVideosVideoIdAudioTracks(videoId) {
      return this.postVideosVideoIdAudioTracksWithHttpInfo(videoId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Bulk upsert video subtitles
     * Replace all subtitles with the provided ones using API key authentication
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Subtitle>} and HTTP response
     */
    postVideosVideoIdSubtitlesWithHttpInfo(videoId) {
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling postVideosVideoIdSubtitles");
      }

      let pathParams = {
        'videoId': videoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = [Subtitle];
      return this.apiClient.callApi(
        '/videos/{videoId}/subtitles', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Bulk upsert video subtitles
     * Replace all subtitles with the provided ones using API key authentication
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Subtitle>}
     */
    postVideosVideoIdSubtitles(videoId) {
      return this.postVideosVideoIdSubtitlesWithHttpInfo(videoId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Upsert video audio track
     * Add or replace an audio track for a specific language using API key authentication
     * @param {String} videoId Video ID
     * @param {String} langCode Language Code (BCP 47)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AudioTrack} and HTTP response
     */
    putVideosVideoIdAudioTracksLangCodeWithHttpInfo(videoId, langCode) {
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling putVideosVideoIdAudioTracksLangCode");
      }
      // verify the required parameter 'langCode' is set
      if (langCode === undefined || langCode === null) {
        throw new Error("Missing the required parameter 'langCode' when calling putVideosVideoIdAudioTracksLangCode");
      }

      let pathParams = {
        'videoId': videoId,
        'lang_code': langCode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = AudioTrack;
      return this.apiClient.callApi(
        '/videos/{videoId}/audio-tracks/{lang_code}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Upsert video audio track
     * Add or replace an audio track for a specific language using API key authentication
     * @param {String} videoId Video ID
     * @param {String} langCode Language Code (BCP 47)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AudioTrack}
     */
    putVideosVideoIdAudioTracksLangCode(videoId, langCode) {
      return this.putVideosVideoIdAudioTracksLangCodeWithHttpInfo(videoId, langCode)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update video chapters
     * Replace all chapters for a video (atomic PUT operation) using API key authentication
     * @param {String} videoId Video ID
     * @param {module:model/PutVideosVideoIdChaptersRequest} putVideosVideoIdChaptersRequest Chapters array
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UpdateChaptersResponse} and HTTP response
     */
    putVideosVideoIdChaptersWithHttpInfo(videoId, putVideosVideoIdChaptersRequest) {
      let postBody = putVideosVideoIdChaptersRequest;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling putVideosVideoIdChapters");
      }
      // verify the required parameter 'putVideosVideoIdChaptersRequest' is set
      if (putVideosVideoIdChaptersRequest === undefined || putVideosVideoIdChaptersRequest === null) {
        throw new Error("Missing the required parameter 'putVideosVideoIdChaptersRequest' when calling putVideosVideoIdChapters");
      }

      let pathParams = {
        'videoId': videoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UpdateChaptersResponse;
      return this.apiClient.callApi(
        '/videos/{videoId}/chapters', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update video chapters
     * Replace all chapters for a video (atomic PUT operation) using API key authentication
     * @param {String} videoId Video ID
     * @param {module:model/PutVideosVideoIdChaptersRequest} putVideosVideoIdChaptersRequest Chapters array
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UpdateChaptersResponse}
     */
    putVideosVideoIdChapters(videoId, putVideosVideoIdChaptersRequest) {
      return this.putVideosVideoIdChaptersWithHttpInfo(videoId, putVideosVideoIdChaptersRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Upsert video subtitle
     * Add or replace a subtitle for a specific language using API key authentication
     * @param {String} videoId Video ID
     * @param {String} langCode Language Code (BCP 47)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Subtitle} and HTTP response
     */
    putVideosVideoIdSubtitlesLangCodeWithHttpInfo(videoId, langCode) {
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling putVideosVideoIdSubtitlesLangCode");
      }
      // verify the required parameter 'langCode' is set
      if (langCode === undefined || langCode === null) {
        throw new Error("Missing the required parameter 'langCode' when calling putVideosVideoIdSubtitlesLangCode");
      }

      let pathParams = {
        'videoId': videoId,
        'lang_code': langCode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Subtitle;
      return this.apiClient.callApi(
        '/videos/{videoId}/subtitles/{lang_code}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Upsert video subtitle
     * Add or replace a subtitle for a specific language using API key authentication
     * @param {String} videoId Video ID
     * @param {String} langCode Language Code (BCP 47)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Subtitle}
     */
    putVideosVideoIdSubtitlesLangCode(videoId, langCode) {
      return this.putVideosVideoIdSubtitlesLangCodeWithHttpInfo(videoId, langCode)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update video thumbnail
     * Update the thumbnail image for an existing video using API key authentication
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Video} and HTTP response
     */
    putVideosVideoIdThumbnailWithHttpInfo(videoId) {
      let postBody = null;
      // verify the required parameter 'videoId' is set
      if (videoId === undefined || videoId === null) {
        throw new Error("Missing the required parameter 'videoId' when calling putVideosVideoIdThumbnail");
      }

      let pathParams = {
        'videoId': videoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Video;
      return this.apiClient.callApi(
        '/videos/{videoId}/thumbnail', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update video thumbnail
     * Update the thumbnail image for an existing video using API key authentication
     * @param {String} videoId Video ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Video}
     */
    putVideosVideoIdThumbnail(videoId) {
      return this.putVideosVideoIdThumbnailWithHttpInfo(videoId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
