/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**

RIXL handles video processing, ingestion and global delivery so you don't have to.
With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 * OpenAPI spec version: 2.0
 */

export type GithubComRixlhqApiDbSqlcVideoQuality =
  (typeof GithubComRixlhqApiDbSqlcVideoQuality)[keyof typeof GithubComRixlhqApiDbSqlcVideoQuality];

export const GithubComRixlhqApiDbSqlcVideoQuality = {
  VideoQualityBasic: "basic",
  VideoQualityShorts: "shorts",
  VideoQualityPro: "pro",
} as const;
