/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**

RIXL handles video processing, ingestion and global delivery so you don't have to.
With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 * OpenAPI spec version: 2.0
 */

export type ListParams = {
  /**
   * Maximum number of items to return in a single request. <br> **Default:** `25`
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
   * @minimum 0
   */
  offset?: number;
};

export type ListParams = {
  /**
   * Maximum number of items to return in a single request. <br> **Default:** `25`
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
   * @minimum 0
   */
  offset?: number;
  /**
   * Field to sort by (created_at, name, size, updated_at)
   */
  sort?: string;
  /**
   * Sort order (asc, desc)
   */
  order?: string;
};

export type ListParams = {
  /**
   * Maximum number of items to return in a single request. <br> **Default:** `25`
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
   * @minimum 0
   */
  offset?: number;
  /**
   * Field to sort by (created_at, name, size, updated_at, duration)
   */
  sort?: string;
  /**
   * Sort order (asc, desc)
   */
  order?: string;
};
