/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PostType.
* @enum {}
* @readonly
*/
export default class PostType {
    
        /**
         * value: "image"
         * @const
         */
        "PostTypeImage" = "image";

    
        /**
         * value: "video"
         * @const
         */
        "PostTypeVideo" = "video";

    

    /**
    * Returns a <code>PostType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PostType} The enum <code>PostType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

