/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**

RIXL handles video processing, ingestion and global delivery so you don't have to.
With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 * OpenAPI spec version: 2.0
 */
import type {GithubComRixlhqApiInternalErrorsErrorResponse, ListByCreatorParams, PaginationPaginatedResponsePost} from "../model";

export type listByCreatorResponse200 = {
  data: PaginationPaginatedResponsePost;
  status: 200;
};

export type listByCreatorResponse400 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 400;
};

export type listByCreatorResponse500 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 500;
};

export type listByCreatorResponseSuccess = listByCreatorResponse200 & {
  headers: Headers;
};
export type listByCreatorResponseError = (listByCreatorResponse400 | listByCreatorResponse500) & {
  headers: Headers;
};

export type listByCreatorResponse = listByCreatorResponseSuccess | listByCreatorResponseError;

export const getListByCreatorUrl = (feedId: string, creatorId: string, params?: ListByCreatorParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/feeds/${feedId}/creators/${creatorId}?${stringifiedParams}`
    : `/feeds/${feedId}/creators/${creatorId}`;
};

/**
 * Retrieve posts in a feed by a specific creator, with pagination.
 * @summary List posts by creator
 */
export const listByCreator = async (
  feedId: string,
  creatorId: string,
  params?: ListByCreatorParams,
  options?: RequestInit
): Promise<listByCreatorResponse> => {
  const res = await fetch(getListByCreatorUrl(feedId, creatorId, params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listByCreatorResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as listByCreatorResponse;
};
