/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**

RIXL handles video processing, ingestion and global delivery so you don't have to.
With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 * OpenAPI spec version: 2.0
 */
import type {
  AudioTrack,
  AudioTrackDelete,
  GithubComRixlhqApiInternalErrorsErrorResponse,
  GithubComRixlhqApiInternalVideosHandlerUploadCompleteRequest,
  GithubComRixlhqApiInternalVideosHandlerUploadInitResponse,
  InternalVideosHandlerSubtitlesLanguageResponse,
  ListParams,
  PaginationPaginatedResponseVideo,
  ReplaceAudioTracksBody,
  ReplaceSubtitlesBody,
  Subtitle,
  SubtitleDelete,
  UpdateAudioTrackByLanguageBody,
  UpdateChaptersRequest,
  UpdateChaptersResponse,
  UpdateSubtitleByLanguageBody,
  UpdateThumbnailBody,
  Video,
  VideoUploadInitRequest,
} from "../model";

export type listResponse200 = {
  data: PaginationPaginatedResponseVideo;
  status: 200;
};

export type listResponse400 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 400;
};

export type listResponse401 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 401;
};

export type listResponse403 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 403;
};

export type listResponse500 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 500;
};

export type listResponseSuccess = listResponse200 & {
  headers: Headers;
};
export type listResponseError = (listResponse400 | listResponse401 | listResponse403 | listResponse500) & {
  headers: Headers;
};

export type listResponse = listResponseSuccess | listResponseError;

export const getListUrl = (params?: ListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/videos?${stringifiedParams}` : `/videos`;
};

/**
 * Retrieve all videos for a specific project, with pagination and sorting.
 * @summary List videos for a project
 */
export const list = async (params?: ListParams, options?: RequestInit): Promise<listResponse> => {
  const res = await fetch(getListUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as listResponse;
};

export type getResponse200 = {
  data: Video;
  status: 200;
};

export type getResponse400 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 400;
};

export type getResponse401 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 401;
};

export type getResponse403 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 403;
};

export type getResponse404 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 404;
};

export type getResponse500 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 500;
};

export type getResponseSuccess = getResponse200 & {
  headers: Headers;
};
export type getResponseError = (getResponse400 | getResponse401 | getResponse403 | getResponse404 | getResponse500) & {
  headers: Headers;
};

export type getResponse = getResponseSuccess | getResponseError;

export const getGetUrl = (videoId: string) => {
  return `/videos/${videoId}`;
};

/**
 * Retrieve a video by its ID for a specific project.
 * @summary Get a video
 */
export const get = async (videoId: string, options?: RequestInit): Promise<getResponse> => {
  const res = await fetch(getGetUrl(videoId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as getResponse;
};

export type _deleteResponse204 = {
  data: void;
  status: 204;
};

export type _deleteResponse400 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 400;
};

export type _deleteResponse401 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 401;
};

export type _deleteResponse403 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 403;
};

export type _deleteResponse404 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 404;
};

export type _deleteResponse500 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 500;
};

export type _deleteResponseSuccess = _deleteResponse204 & {
  headers: Headers;
};
export type _deleteResponseError = (
  | _deleteResponse400
  | _deleteResponse401
  | _deleteResponse403
  | _deleteResponse404
  | _deleteResponse500
) & {
  headers: Headers;
};

export type _deleteResponse = _deleteResponseSuccess | _deleteResponseError;

export const getDeleteUrl = (videoId: string) => {
  return `/videos/${videoId}/delete`;
};

/**
 * Delete a video by its ID within a project
 * @summary Delete video
 */
export const _delete = async (videoId: string, options?: RequestInit): Promise<_deleteResponse> => {
  const res = await fetch(getDeleteUrl(videoId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: _deleteResponse["data"] = body ? JSON.parse(body) : undefined;
  return {data, status: res.status, headers: res.headers} as _deleteResponse;
};

export type uploadCompleteResponse200 = {
  data: Video;
  status: 200;
};

export type uploadCompleteResponse400 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 400;
};

export type uploadCompleteResponse401 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 401;
};

export type uploadCompleteResponse403 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 403;
};

export type uploadCompleteResponse404 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 404;
};

export type uploadCompleteResponse500 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 500;
};

export type uploadCompleteResponseSuccess = uploadCompleteResponse200 & {
  headers: Headers;
};
export type uploadCompleteResponseError = (
  | uploadCompleteResponse400
  | uploadCompleteResponse401
  | uploadCompleteResponse403
  | uploadCompleteResponse404
  | uploadCompleteResponse500
) & {
  headers: Headers;
};

export type uploadCompleteResponse = uploadCompleteResponseSuccess | uploadCompleteResponseError;

export const getUploadCompleteUrl = () => {
  return `/videos/upload/complete`;
};

/**
 * Mark a video upload as complete after successful upload to storage using API key authentication
 * @summary Upload: Mark as complete
 */
export const uploadComplete = async (
  githubComRixlhqApiInternalVideosHandlerUploadCompleteRequest: GithubComRixlhqApiInternalVideosHandlerUploadCompleteRequest,
  options?: RequestInit
): Promise<uploadCompleteResponse> => {
  const res = await fetch(getUploadCompleteUrl(), {
    ...options,
    method: "POST",
    headers: {"Content-Type": "application/json", ...options?.headers},
    body: JSON.stringify(githubComRixlhqApiInternalVideosHandlerUploadCompleteRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: uploadCompleteResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as uploadCompleteResponse;
};

export type uploadInitResponse200 = {
  data: GithubComRixlhqApiInternalVideosHandlerUploadInitResponse;
  status: 200;
};

export type uploadInitResponse400 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 400;
};

export type uploadInitResponse401 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 401;
};

export type uploadInitResponse403 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 403;
};

export type uploadInitResponse500 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 500;
};

export type uploadInitResponseSuccess = uploadInitResponse200 & {
  headers: Headers;
};
export type uploadInitResponseError = (uploadInitResponse400 | uploadInitResponse401 | uploadInitResponse403 | uploadInitResponse500) & {
  headers: Headers;
};

export type uploadInitResponse = uploadInitResponseSuccess | uploadInitResponseError;

export const getUploadInitUrl = () => {
  return `/videos/upload/init`;
};

/**
 * Initialize a video upload and get presigned URLs for video and poster using API key authentication
 * @summary Upload: Init
 */
export const uploadInit = async (videoUploadInitRequest: VideoUploadInitRequest, options?: RequestInit): Promise<uploadInitResponse> => {
  const res = await fetch(getUploadInitUrl(), {
    ...options,
    method: "POST",
    headers: {"Content-Type": "application/json", ...options?.headers},
    body: JSON.stringify(videoUploadInitRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: uploadInitResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as uploadInitResponse;
};

export type deleteAudioTracksResponse200 = {
  data: AudioTrackDelete;
  status: 200;
};

export type deleteAudioTracksResponseSuccess = deleteAudioTracksResponse200 & {
  headers: Headers;
};

export type deleteAudioTracksResponse = deleteAudioTracksResponseSuccess;

export const getDeleteAudioTracksUrl = (videoId: string) => {
  return `/videos/${videoId}/audio-tracks`;
};

/**
 * Remove all additional audio tracks from a video using API key authentication
 * @summary Delete all audio tracks
 */
export const deleteAudioTracks = async (videoId: string, options?: RequestInit): Promise<deleteAudioTracksResponse> => {
  const res = await fetch(getDeleteAudioTracksUrl(videoId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteAudioTracksResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as deleteAudioTracksResponse;
};

export type replaceAudioTracksResponse200 = {
  data: AudioTrack[];
  status: 200;
};

export type replaceAudioTracksResponseSuccess = replaceAudioTracksResponse200 & {
  headers: Headers;
};

export type replaceAudioTracksResponse = replaceAudioTracksResponseSuccess;

export const getReplaceAudioTracksUrl = (videoId: string) => {
  return `/videos/${videoId}/audio-tracks`;
};

/**
 * Replace all audio tracks with the provided ones using API key authentication
 * @summary Bulk upsert video audio tracks
 */
export const replaceAudioTracks = async (
  videoId: string,
  replaceAudioTracksBody: ReplaceAudioTracksBody,
  options?: RequestInit
): Promise<replaceAudioTracksResponse> => {
  const formData = new FormData();
  replaceAudioTracksBody.files.forEach((value) => formData.append(`files`, value));
  formData.append(`labels`, replaceAudioTracksBody.labels);
  formData.append(`language_codes`, replaceAudioTracksBody.language_codes);

  const res = await fetch(getReplaceAudioTracksUrl(videoId), {
    ...options,
    method: "POST",
    body: formData,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: replaceAudioTracksResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as replaceAudioTracksResponse;
};

export type deleteAudioTrackResponse200 = {
  data: AudioTrackDelete;
  status: 200;
};

export type deleteAudioTrackResponse401 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 401;
};

export type deleteAudioTrackResponse403 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 403;
};

export type deleteAudioTrackResponse404 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 404;
};

export type deleteAudioTrackResponse500 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 500;
};

export type deleteAudioTrackResponseSuccess = deleteAudioTrackResponse200 & {
  headers: Headers;
};
export type deleteAudioTrackResponseError = (
  | deleteAudioTrackResponse401
  | deleteAudioTrackResponse403
  | deleteAudioTrackResponse404
  | deleteAudioTrackResponse500
) & {
  headers: Headers;
};

export type deleteAudioTrackResponse = deleteAudioTrackResponseSuccess | deleteAudioTrackResponseError;

export const getDeleteAudioTrackUrl = (videoId: string, trackId: string) => {
  return `/videos/${videoId}/audio-tracks/${trackId}`;
};

/**
 * Remove an additional audio track from a video using API key authentication
 * @summary Delete audio track
 */
export const deleteAudioTrack = async (videoId: string, trackId: string, options?: RequestInit): Promise<deleteAudioTrackResponse> => {
  const res = await fetch(getDeleteAudioTrackUrl(videoId, trackId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteAudioTrackResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as deleteAudioTrackResponse;
};

export type deleteAudioTrackByLanguageResponse200 = {
  data: AudioTrackDelete;
  status: 200;
};

export type deleteAudioTrackByLanguageResponseSuccess = deleteAudioTrackByLanguageResponse200 & {
  headers: Headers;
};

export type deleteAudioTrackByLanguageResponse = deleteAudioTrackByLanguageResponseSuccess;

export const getDeleteAudioTrackByLanguageUrl = (videoId: string, langCode: string) => {
  return `/videos/${videoId}/audio-tracks/language/${langCode}`;
};

/**
 * Remove an audio track for a specific language using API key authentication
 * @summary Delete audio track by language
 */
export const deleteAudioTrackByLanguage = async (
  videoId: string,
  langCode: string,
  options?: RequestInit
): Promise<deleteAudioTrackByLanguageResponse> => {
  const res = await fetch(getDeleteAudioTrackByLanguageUrl(videoId, langCode), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteAudioTrackByLanguageResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as deleteAudioTrackByLanguageResponse;
};

export type updateAudioTrackByLanguageResponse200 = {
  data: AudioTrack;
  status: 200;
};

export type updateAudioTrackByLanguageResponseSuccess = updateAudioTrackByLanguageResponse200 & {
  headers: Headers;
};

export type updateAudioTrackByLanguageResponse = updateAudioTrackByLanguageResponseSuccess;

export const getUpdateAudioTrackByLanguageUrl = (videoId: string, langCode: string) => {
  return `/videos/${videoId}/audio-tracks/language/${langCode}`;
};

/**
 * Add or replace an audio track for a specific language using API key authentication
 * @summary Upsert video audio track
 */
export const updateAudioTrackByLanguage = async (
  videoId: string,
  langCode: string,
  updateAudioTrackByLanguageBody: UpdateAudioTrackByLanguageBody,
  options?: RequestInit
): Promise<updateAudioTrackByLanguageResponse> => {
  const formData = new FormData();
  formData.append(`file`, updateAudioTrackByLanguageBody.file);
  if (updateAudioTrackByLanguageBody.label !== undefined) {
    formData.append(`label`, updateAudioTrackByLanguageBody.label);
  }

  const res = await fetch(getUpdateAudioTrackByLanguageUrl(videoId, langCode), {
    ...options,
    method: "PUT",
    body: formData,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateAudioTrackByLanguageResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as updateAudioTrackByLanguageResponse;
};

export type deleteChaptersResponse200 = {
  data: UpdateChaptersResponse;
  status: 200;
};

export type deleteChaptersResponse401 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 401;
};

export type deleteChaptersResponse403 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 403;
};

export type deleteChaptersResponse404 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 404;
};

export type deleteChaptersResponse500 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 500;
};

export type deleteChaptersResponseSuccess = deleteChaptersResponse200 & {
  headers: Headers;
};
export type deleteChaptersResponseError = (
  | deleteChaptersResponse401
  | deleteChaptersResponse403
  | deleteChaptersResponse404
  | deleteChaptersResponse500
) & {
  headers: Headers;
};

export type deleteChaptersResponse = deleteChaptersResponseSuccess | deleteChaptersResponseError;

export const getDeleteChaptersUrl = (videoId: string) => {
  return `/videos/${videoId}/chapters`;
};

/**
 * Remove all chapters from a video using API key authentication
 * @summary Delete video chapters
 */
export const deleteChapters = async (videoId: string, options?: RequestInit): Promise<deleteChaptersResponse> => {
  const res = await fetch(getDeleteChaptersUrl(videoId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteChaptersResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as deleteChaptersResponse;
};

export type updateChaptersResponse200 = {
  data: UpdateChaptersResponse;
  status: 200;
};

export type updateChaptersResponse400 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 400;
};

export type updateChaptersResponse401 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 401;
};

export type updateChaptersResponse403 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 403;
};

export type updateChaptersResponse404 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 404;
};

export type updateChaptersResponse500 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 500;
};

export type updateChaptersResponseSuccess = updateChaptersResponse200 & {
  headers: Headers;
};
export type updateChaptersResponseError = (
  | updateChaptersResponse400
  | updateChaptersResponse401
  | updateChaptersResponse403
  | updateChaptersResponse404
  | updateChaptersResponse500
) & {
  headers: Headers;
};

export type updateChaptersResponse = updateChaptersResponseSuccess | updateChaptersResponseError;

export const getUpdateChaptersUrl = (videoId: string) => {
  return `/videos/${videoId}/chapters`;
};

/**
 * Replace all chapters for a video (atomic PUT operation) using API key authentication
 * @summary Update video chapters
 */
export const updateChapters = async (
  videoId: string,
  updateChaptersRequest: UpdateChaptersRequest,
  options?: RequestInit
): Promise<updateChaptersResponse> => {
  const res = await fetch(getUpdateChaptersUrl(videoId), {
    ...options,
    method: "PUT",
    headers: {"Content-Type": "application/json", ...options?.headers},
    body: JSON.stringify(updateChaptersRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateChaptersResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as updateChaptersResponse;
};

export type deleteSubtitlesResponse200 = {
  data: SubtitleDelete;
  status: 200;
};

export type deleteSubtitlesResponseSuccess = deleteSubtitlesResponse200 & {
  headers: Headers;
};

export type deleteSubtitlesResponse = deleteSubtitlesResponseSuccess;

export const getDeleteSubtitlesUrl = (videoId: string) => {
  return `/videos/${videoId}/subtitles`;
};

/**
 * Remove all subtitles from a video using API key authentication
 * @summary Delete all subtitles
 */
export const deleteSubtitles = async (videoId: string, options?: RequestInit): Promise<deleteSubtitlesResponse> => {
  const res = await fetch(getDeleteSubtitlesUrl(videoId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteSubtitlesResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as deleteSubtitlesResponse;
};

export type replaceSubtitlesResponse200 = {
  data: Subtitle[];
  status: 200;
};

export type replaceSubtitlesResponseSuccess = replaceSubtitlesResponse200 & {
  headers: Headers;
};

export type replaceSubtitlesResponse = replaceSubtitlesResponseSuccess;

export const getReplaceSubtitlesUrl = (videoId: string) => {
  return `/videos/${videoId}/subtitles`;
};

/**
 * Replace all subtitles with the provided ones using API key authentication
 * @summary Bulk upsert video subtitles
 */
export const replaceSubtitles = async (
  videoId: string,
  replaceSubtitlesBody: ReplaceSubtitlesBody,
  options?: RequestInit
): Promise<replaceSubtitlesResponse> => {
  const formData = new FormData();
  replaceSubtitlesBody.files.forEach((value) => formData.append(`files`, value));
  formData.append(`labels`, replaceSubtitlesBody.labels);
  formData.append(`language_codes`, replaceSubtitlesBody.language_codes);

  const res = await fetch(getReplaceSubtitlesUrl(videoId), {
    ...options,
    method: "POST",
    body: formData,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: replaceSubtitlesResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as replaceSubtitlesResponse;
};

export type deleteSubtitleResponse200 = {
  data: SubtitleDelete;
  status: 200;
};

export type deleteSubtitleResponse401 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 401;
};

export type deleteSubtitleResponse403 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 403;
};

export type deleteSubtitleResponse404 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 404;
};

export type deleteSubtitleResponse500 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 500;
};

export type deleteSubtitleResponseSuccess = deleteSubtitleResponse200 & {
  headers: Headers;
};
export type deleteSubtitleResponseError = (
  | deleteSubtitleResponse401
  | deleteSubtitleResponse403
  | deleteSubtitleResponse404
  | deleteSubtitleResponse500
) & {
  headers: Headers;
};

export type deleteSubtitleResponse = deleteSubtitleResponseSuccess | deleteSubtitleResponseError;

export const getDeleteSubtitleUrl = (videoId: string, subtitleId: string) => {
  return `/videos/${videoId}/subtitles/${subtitleId}`;
};

/**
 * Remove a subtitle from a video using API key authentication
 * @summary Delete subtitle
 */
export const deleteSubtitle = async (videoId: string, subtitleId: string, options?: RequestInit): Promise<deleteSubtitleResponse> => {
  const res = await fetch(getDeleteSubtitleUrl(videoId, subtitleId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteSubtitleResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as deleteSubtitleResponse;
};

export type deleteSubtitleByLanguageResponse200 = {
  data: SubtitleDelete;
  status: 200;
};

export type deleteSubtitleByLanguageResponseSuccess = deleteSubtitleByLanguageResponse200 & {
  headers: Headers;
};

export type deleteSubtitleByLanguageResponse = deleteSubtitleByLanguageResponseSuccess;

export const getDeleteSubtitleByLanguageUrl = (videoId: string, langCode: string) => {
  return `/videos/${videoId}/subtitles/language/${langCode}`;
};

/**
 * Remove a subtitle for a specific language using API key authentication
 * @summary Delete subtitle by language
 */
export const deleteSubtitleByLanguage = async (
  videoId: string,
  langCode: string,
  options?: RequestInit
): Promise<deleteSubtitleByLanguageResponse> => {
  const res = await fetch(getDeleteSubtitleByLanguageUrl(videoId, langCode), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteSubtitleByLanguageResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as deleteSubtitleByLanguageResponse;
};

export type updateSubtitleByLanguageResponse200 = {
  data: Subtitle;
  status: 200;
};

export type updateSubtitleByLanguageResponseSuccess = updateSubtitleByLanguageResponse200 & {
  headers: Headers;
};

export type updateSubtitleByLanguageResponse = updateSubtitleByLanguageResponseSuccess;

export const getUpdateSubtitleByLanguageUrl = (videoId: string, langCode: string) => {
  return `/videos/${videoId}/subtitles/language/${langCode}`;
};

/**
 * Add or replace a subtitle for a specific language using API key authentication
 * @summary Upsert video subtitle
 */
export const updateSubtitleByLanguage = async (
  videoId: string,
  langCode: string,
  updateSubtitleByLanguageBody: UpdateSubtitleByLanguageBody,
  options?: RequestInit
): Promise<updateSubtitleByLanguageResponse> => {
  const formData = new FormData();
  formData.append(`file`, updateSubtitleByLanguageBody.file);
  if (updateSubtitleByLanguageBody.label !== undefined) {
    formData.append(`label`, updateSubtitleByLanguageBody.label);
  }

  const res = await fetch(getUpdateSubtitleByLanguageUrl(videoId, langCode), {
    ...options,
    method: "PUT",
    body: formData,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateSubtitleByLanguageResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as updateSubtitleByLanguageResponse;
};

export type updateThumbnailResponse200 = {
  data: Video;
  status: 200;
};

export type updateThumbnailResponse400 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 400;
};

export type updateThumbnailResponse401 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 401;
};

export type updateThumbnailResponse403 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 403;
};

export type updateThumbnailResponse404 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 404;
};

export type updateThumbnailResponse500 = {
  data: GithubComRixlhqApiInternalErrorsErrorResponse;
  status: 500;
};

export type updateThumbnailResponseSuccess = updateThumbnailResponse200 & {
  headers: Headers;
};
export type updateThumbnailResponseError = (
  | updateThumbnailResponse400
  | updateThumbnailResponse401
  | updateThumbnailResponse403
  | updateThumbnailResponse404
  | updateThumbnailResponse500
) & {
  headers: Headers;
};

export type updateThumbnailResponse = updateThumbnailResponseSuccess | updateThumbnailResponseError;

export const getUpdateThumbnailUrl = (videoId: string) => {
  return `/videos/${videoId}/thumbnail`;
};

/**
 * Update the thumbnail image for an existing video using API key authentication
 * @summary Update video thumbnail
 */
export const updateThumbnail = async (
  videoId: string,
  updateThumbnailBody: UpdateThumbnailBody,
  options?: RequestInit
): Promise<updateThumbnailResponse> => {
  const formData = new FormData();
  formData.append(`thumbnail`, updateThumbnailBody.thumbnail);

  const res = await fetch(getUpdateThumbnailUrl(videoId), {
    ...options,
    method: "PUT",
    body: formData,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateThumbnailResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as updateThumbnailResponse;
};

export type listLanguagesResponse200 = {
  data: InternalVideosHandlerSubtitlesLanguageResponse[];
  status: 200;
};

export type listLanguagesResponseSuccess = listLanguagesResponse200 & {
  headers: Headers;
};

export type listLanguagesResponse = listLanguagesResponseSuccess;

export const getListLanguagesUrl = () => {
  return `/videos/languages`;
};

/**
 * Get list of supported languages for subtitles
 * @summary List available subtitle languages
 */
export const listLanguages = async (options?: RequestInit): Promise<listLanguagesResponse> => {
  const res = await fetch(getListLanguagesUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listLanguagesResponse["data"] = body ? JSON.parse(body) : {};
  return {data, status: res.status, headers: res.headers} as listLanguagesResponse;
};
