/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AudioTrack from './model/AudioTrack';
import AudioTrackDelete from './model/AudioTrackDelete';
import Chapter from './model/Chapter';
import File from './model/File';
import FileStatus from './model/FileStatus';
import GithubComQeeqezApiDbSqlcPlanType from './model/GithubComQeeqezApiDbSqlcPlanType';
import GithubComQeeqezApiDbSqlcVideoQuality from './model/GithubComQeeqezApiDbSqlcVideoQuality';
import GithubComQeeqezApiInternalErrorsErrorResponse from './model/GithubComQeeqezApiInternalErrorsErrorResponse';
import GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest from './model/GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest';
import GithubComQeeqezApiInternalVideosHandlerUploadInitResponse from './model/GithubComQeeqezApiInternalVideosHandlerUploadInitResponse';
import GithubComQeeqezApiInternalVideosTypesChapterInput from './model/GithubComQeeqezApiInternalVideosTypesChapterInput';
import Image from './model/Image';
import InternalVideosHandlerSubtitlesLanguageResponse from './model/InternalVideosHandlerSubtitlesLanguageResponse';
import PaginationPaginatedResponseVideo from './model/PaginationPaginatedResponseVideo';
import PaginationPagination from './model/PaginationPagination';
import Subtitle from './model/Subtitle';
import SubtitleDelete from './model/SubtitleDelete';
import UpdateChaptersRequest from './model/UpdateChaptersRequest';
import UpdateChaptersResponse from './model/UpdateChaptersResponse';
import Video from './model/Video';
import VideoUploadInitRequest from './model/VideoUploadInitRequest';
import VideosUploadCompletePostRequest from './model/VideosUploadCompletePostRequest';
import VideosUploadInitPostRequest from './model/VideosUploadInitPostRequest';
import VideosVideoIdChaptersPutRequest from './model/VideosVideoIdChaptersPutRequest';
import VideosApi from './api/VideosApi';


/**
* **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don&#39;t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var RixlApi = require('index'); // See note below*.
* var xxxSvc = new RixlApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new RixlApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new RixlApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new RixlApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AudioTrack model constructor.
     * @property {module:model/AudioTrack}
     */
    AudioTrack,

    /**
     * The AudioTrackDelete model constructor.
     * @property {module:model/AudioTrackDelete}
     */
    AudioTrackDelete,

    /**
     * The Chapter model constructor.
     * @property {module:model/Chapter}
     */
    Chapter,

    /**
     * The File model constructor.
     * @property {module:model/File}
     */
    File,

    /**
     * The FileStatus model constructor.
     * @property {module:model/FileStatus}
     */
    FileStatus,

    /**
     * The GithubComQeeqezApiDbSqlcPlanType model constructor.
     * @property {module:model/GithubComQeeqezApiDbSqlcPlanType}
     */
    GithubComQeeqezApiDbSqlcPlanType,

    /**
     * The GithubComQeeqezApiDbSqlcVideoQuality model constructor.
     * @property {module:model/GithubComQeeqezApiDbSqlcVideoQuality}
     */
    GithubComQeeqezApiDbSqlcVideoQuality,

    /**
     * The GithubComQeeqezApiInternalErrorsErrorResponse model constructor.
     * @property {module:model/GithubComQeeqezApiInternalErrorsErrorResponse}
     */
    GithubComQeeqezApiInternalErrorsErrorResponse,

    /**
     * The GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest model constructor.
     * @property {module:model/GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest}
     */
    GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest,

    /**
     * The GithubComQeeqezApiInternalVideosHandlerUploadInitResponse model constructor.
     * @property {module:model/GithubComQeeqezApiInternalVideosHandlerUploadInitResponse}
     */
    GithubComQeeqezApiInternalVideosHandlerUploadInitResponse,

    /**
     * The GithubComQeeqezApiInternalVideosTypesChapterInput model constructor.
     * @property {module:model/GithubComQeeqezApiInternalVideosTypesChapterInput}
     */
    GithubComQeeqezApiInternalVideosTypesChapterInput,

    /**
     * The Image model constructor.
     * @property {module:model/Image}
     */
    Image,

    /**
     * The InternalVideosHandlerSubtitlesLanguageResponse model constructor.
     * @property {module:model/InternalVideosHandlerSubtitlesLanguageResponse}
     */
    InternalVideosHandlerSubtitlesLanguageResponse,

    /**
     * The PaginationPaginatedResponseVideo model constructor.
     * @property {module:model/PaginationPaginatedResponseVideo}
     */
    PaginationPaginatedResponseVideo,

    /**
     * The PaginationPagination model constructor.
     * @property {module:model/PaginationPagination}
     */
    PaginationPagination,

    /**
     * The Subtitle model constructor.
     * @property {module:model/Subtitle}
     */
    Subtitle,

    /**
     * The SubtitleDelete model constructor.
     * @property {module:model/SubtitleDelete}
     */
    SubtitleDelete,

    /**
     * The UpdateChaptersRequest model constructor.
     * @property {module:model/UpdateChaptersRequest}
     */
    UpdateChaptersRequest,

    /**
     * The UpdateChaptersResponse model constructor.
     * @property {module:model/UpdateChaptersResponse}
     */
    UpdateChaptersResponse,

    /**
     * The Video model constructor.
     * @property {module:model/Video}
     */
    Video,

    /**
     * The VideoUploadInitRequest model constructor.
     * @property {module:model/VideoUploadInitRequest}
     */
    VideoUploadInitRequest,

    /**
     * The VideosUploadCompletePostRequest model constructor.
     * @property {module:model/VideosUploadCompletePostRequest}
     */
    VideosUploadCompletePostRequest,

    /**
     * The VideosUploadInitPostRequest model constructor.
     * @property {module:model/VideosUploadInitPostRequest}
     */
    VideosUploadInitPostRequest,

    /**
     * The VideosVideoIdChaptersPutRequest model constructor.
     * @property {module:model/VideosVideoIdChaptersPutRequest}
     */
    VideosVideoIdChaptersPutRequest,

    /**
    * The VideosApi service constructor.
    * @property {module:api/VideosApi}
    */
    VideosApi
};
