/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GithubComQeeqezApiInternalErrorsErrorResponse from '../models/GithubComQeeqezApiInternalErrorsErrorResponse';
import Image from '../models/Image';
import InternalImagesHandlerCompleteRequest from '../models/InternalImagesHandlerCompleteRequest';
import InternalImagesHandlerInitResponse from '../models/InternalImagesHandlerInitResponse';
import InternalImagesHandlerUploadInitRequest from '../models/InternalImagesHandlerUploadInitRequest';
import PaginationPaginatedResponseImage from '../models/PaginationPaginatedResponseImage';

/**
* Images service.
* @module services/ImagesApi
* @version 2.0.0
*/
export default class ImagesApi {

    /**
    * Constructs a new ImagesApi. 
    * @alias module:services/ImagesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Delete image
     * delete an image by marking it as deleted
     * @param {String} imageId Image ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteImagesImageIdWithHttpInfo(imageId) {
      let postBody = null;
      // verify the required parameter 'imageId' is set
      if (imageId === undefined || imageId === null) {
        throw new Error("Missing the required parameter 'imageId' when calling deleteImagesImageId");
      }

      let pathParams = {
        'imageId': imageId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/images/{imageId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete image
     * delete an image by marking it as deleted
     * @param {String} imageId Image ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteImagesImageId(imageId) {
      return this.deleteImagesImageIdWithHttpInfo(imageId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List images for a project
     * Retrieve all images for a specific project, with pagination and sorting.
     * @param {Object} opts Optional parameters
     * @param {Number} [limit = 25)] Maximum number of items to return in a single request. <br> **Default:** `25`
     * @param {Number} [offset = 0)] Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
     * @param {String} [sort] Field to sort by (created_at, name, size, updated_at)
     * @param {String} [order] Sort order (asc, desc)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/PaginationPaginatedResponseImage} and HTTP response
     */
    getImagesWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset'],
        'sort': opts['sort'],
        'order': opts['order']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginationPaginatedResponseImage;
      return this.apiClient.callApi(
        '/images', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List images for a project
     * Retrieve all images for a specific project, with pagination and sorting.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Maximum number of items to return in a single request. <br> **Default:** `25` (default to 25)
     * @param {Number} opts.offset Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0` (default to 0)
     * @param {String} opts.sort Field to sort by (created_at, name, size, updated_at)
     * @param {String} opts.order Sort order (asc, desc)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/PaginationPaginatedResponseImage}
     */
    getImages(opts) {
      return this.getImagesWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get image
     * Retrieve an image by its ID for a specific project.
     * @param {String} imageId Image ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/Image} and HTTP response
     */
    getImagesImageIdWithHttpInfo(imageId) {
      let postBody = null;
      // verify the required parameter 'imageId' is set
      if (imageId === undefined || imageId === null) {
        throw new Error("Missing the required parameter 'imageId' when calling getImagesImageId");
      }

      let pathParams = {
        'imageId': imageId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Image;
      return this.apiClient.callApi(
        '/images/{imageId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get image
     * Retrieve an image by its ID for a specific project.
     * @param {String} imageId Image ID
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/Image}
     */
    getImagesImageId(imageId) {
      return this.getImagesImageIdWithHttpInfo(imageId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Upload: Mark as complete
     * Complete the upload process and create the image record using API key authentication
     * @param {module:models/InternalImagesHandlerCompleteRequest} request Upload completion request
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/Image} and HTTP response
     */
    postImagesUploadCompleteWithHttpInfo(request) {
      let postBody = request;
      // verify the required parameter 'request' is set
      if (request === undefined || request === null) {
        throw new Error("Missing the required parameter 'request' when calling postImagesUploadComplete");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Image;
      return this.apiClient.callApi(
        '/images/upload/complete', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Upload: Mark as complete
     * Complete the upload process and create the image record using API key authentication
     * @param {module:models/InternalImagesHandlerCompleteRequest} request Upload completion request
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/Image}
     */
    postImagesUploadComplete(request) {
      return this.postImagesUploadCompleteWithHttpInfo(request)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Upload: Init
     * Initialize a presigned URL upload for an image file using API key authentication
     * @param {module:models/InternalImagesHandlerUploadInitRequest} request Upload initialization request
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/InternalImagesHandlerInitResponse} and HTTP response
     */
    postImagesUploadInitWithHttpInfo(request) {
      let postBody = request;
      // verify the required parameter 'request' is set
      if (request === undefined || request === null) {
        throw new Error("Missing the required parameter 'request' when calling postImagesUploadInit");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InternalImagesHandlerInitResponse;
      return this.apiClient.callApi(
        '/images/upload/init', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Upload: Init
     * Initialize a presigned URL upload for an image file using API key authentication
     * @param {module:models/InternalImagesHandlerUploadInitRequest} request Upload initialization request
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/InternalImagesHandlerInitResponse}
     */
    postImagesUploadInit(request) {
      return this.postImagesUploadInitWithHttpInfo(request)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
