// Side-effect import: registers this copy's client so connect() configures it
// even when the consumer only ever imports `client` or a generated request
// function, never `connect`. Without the registration a bundler-duplicated copy
// silently keeps the generator's placeholder baseUrl.
import "./client-registry";

export {createClient} from "./generated/client";
export {client} from "./generated/client.gen";
export * from "./generated/types.gen";
export * from "./generated/sdk.gen";

// Unified entry point
export {connect, type ConnectConfig, type AuthConfig} from "./connect";

// Auth surface — state machine, stores, and domain functions
export {
  isLogged,
  getToken,
  login,
  logout,
  authError,
  clearAuthError,
  requiresAction,
  limitedAccessToken,
  setLimitedAccessState,
  clearLimitedAccessState,
  user,
  initClient,
  type AuthClientConfig,
  type GoogleProviderConfig,
  type AppleProviderConfig,
  type TelegramProviderConfig,
  leaveOrganization,
  listActiveMemberships,
  listPendingMemberships,
  updateActiveMembership,
  listOrganizationMembers,
  inviteMember,
  updateMemberRole,
  deleteMember,
  MembershipRole,
  type AssignableRole,
  MembershipState,
  respondToInvitation,
  resendMemberInvite,
  publicRespondToInvitation,
  type Member,
  type Membership,
  type MembershipApplication,
  type InviteMemberRequest,
  type UpdateMemberRoleRequest,
  type ResendInviteMemberRequest,
  updateFullName,
  updateUsername,
  getUserInfo,
  verifyUserOTP,
  setupUserOTP,
  deleteUserOTP,
  getOTPStatus,
  regenerateBackupCodes,
  type OTPSetup,
  type OTPStatusResponse,
  type BackupCodes,
  type UserInfo,
  updateOrgName,
  updateOrgUsername,
  listSocials,
  connectSocial,
  disconnectSocial,
  type ConnectedProvider,
  type ProviderType,
  registerWithEmail,
  loginWithEmail,
  verifyTOTPForLogin,
  resendEmailVerificationCode,
  initiateEmailChange,
  addEmail,
  verifyEmailWithCode,
  getEmailVerificationStatus,
  sendPasswordResetEmail,
  confirmPasswordReset,
  type VerifyStatusResponse,
  type RegistrationResponse,
  type LoginOTPVerifyRequest,
  type LoginErrorResponse,
  type LoginErrorCode,
  type OAuth2ErrorResponse,
  getDomainStatus,
  initiateDomainVerification,
  checkDomainVerification,
  updateAutoJoin,
  removeDomain,
  DomainStatus,
  type DomainResponse,
  type AddDomainRequest,
  type UpdateAutoJoinRequest,
  type AutoJoinSetting,
  getBlogSubscriptionStatus,
  subscribeToBlog,
  unsubscribeFromBlog,
  type BlogSubscriptionStatus,
  beginPasskeyLogin,
  beginPasskeyRegistration,
  decodeRequestOptions,
  deletePasskey,
  finishPasskeyLogin,
  finishPasskeyRegistration,
  listPasskeys,
  PasskeyUnavailableError,
  renamePasskey,
  verifyPasskeyForLogin,
  type Passkey,
  type PasskeyBeginLogin,
  type PasskeyBeginRegistration,
  type PasskeyRegistrationResult,
  type TwoFactorResponse,
  type TwoFactorAuthMethod,
  type User,
  type TokenResponse,
  type LimitedScopeTokenResponse,
  type RequiresAction,
} from "./auth";
