// This file is auto-generated by @hey-api/openapi-ts

import {type Client, formDataBodySerializer, type Options as Options2, type TDataShape} from "./client";
import {client} from "./client.gen";
import type {
  Delete2Data,
  Delete2Errors,
  Delete2Responses,
  DeleteAudioTrackByLanguageData,
  DeleteAudioTrackByLanguageResponses,
  DeleteAudioTrackData,
  DeleteAudioTrackErrors,
  DeleteAudioTrackResponses,
  DeleteAudioTracksData,
  DeleteAudioTracksResponses,
  DeleteChaptersData,
  DeleteChaptersErrors,
  DeleteChaptersResponses,
  DeleteData,
  DeleteErrors,
  DeleteResponses,
  DeleteSubtitleByLanguageData,
  DeleteSubtitleByLanguageResponses,
  DeleteSubtitleData,
  DeleteSubtitleErrors,
  DeleteSubtitleResponses,
  DeleteSubtitlesData,
  DeleteSubtitlesResponses,
  Get2Data,
  Get2Errors,
  Get2Responses,
  Get3Data,
  Get3Errors,
  Get3Responses,
  GetData,
  GetErrors,
  GetResponses,
  List2Data,
  List2Errors,
  List2Responses,
  List3Data,
  List3Errors,
  List3Responses,
  ListByCreatorData,
  ListByCreatorErrors,
  ListByCreatorResponses,
  ListData,
  ListErrors,
  ListLanguagesData,
  ListLanguagesResponses,
  ListResponses,
  ReplaceAudioTracksData,
  ReplaceAudioTracksResponses,
  ReplaceSubtitlesData,
  ReplaceSubtitlesResponses,
  UpdateAudioTrackByLanguageData,
  UpdateAudioTrackByLanguageResponses,
  UpdateChaptersData,
  UpdateChaptersErrors,
  UpdateChaptersResponses,
  UpdateSubtitleByLanguageData,
  UpdateSubtitleByLanguageResponses,
  UpdateThumbnailData,
  UpdateThumbnailErrors,
  UpdateThumbnailResponses,
  UploadComplete2Data,
  UploadComplete2Errors,
  UploadComplete2Responses,
  UploadCompleteData,
  UploadCompleteErrors,
  UploadCompleteResponses,
  UploadInit2Data,
  UploadInit2Errors,
  UploadInit2Responses,
  UploadInitData,
  UploadInitErrors,
  UploadInitResponses,
} from "./types.gen";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<
  TData,
  ThrowOnError,
  TResponse
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class Feeds {
  /**
   * List posts in a feed
   *
   * Retrieve posts in a feed, with pagination.
   */
  public static list<ThrowOnError extends boolean = false>(options: Options<ListData, ThrowOnError>) {
    return (options.client ?? client).get<ListResponses, ListErrors, ThrowOnError>({url: "/feeds/{feedId}", ...options});
  }

  /**
   * Get a post
   *
   * Retrieve a post from feed by its ID
   */
  public static get<ThrowOnError extends boolean = false>(options: Options<GetData, ThrowOnError>) {
    return (options.client ?? client).get<GetResponses, GetErrors, ThrowOnError>({url: "/feeds/{feedId}/{postId}", ...options});
  }

  /**
   * List posts by creator
   *
   * Retrieve posts in a feed by a specific creator, with pagination.
   */
  public static listByCreator<ThrowOnError extends boolean = false>(options: Options<ListByCreatorData, ThrowOnError>) {
    return (options.client ?? client).get<ListByCreatorResponses, ListByCreatorErrors, ThrowOnError>({
      url: "/feeds/{feedId}/creators/{creatorId}",
      ...options,
    });
  }
}

export class Images {
  /**
   * List images for a project
   *
   * Retrieve all images for a specific project, with pagination and sorting.
   */
  public static list<ThrowOnError extends boolean = false>(options?: Options<List2Data, ThrowOnError>) {
    return (options?.client ?? client).get<List2Responses, List2Errors, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/images",
      ...options,
    });
  }

  /**
   * Delete image
   *
   * delete an image by marking it as deleted
   */
  public static delete<ThrowOnError extends boolean = false>(options: Options<DeleteData, ThrowOnError>) {
    return (options.client ?? client).delete<DeleteResponses, DeleteErrors, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/images/{imageId}",
      ...options,
    });
  }

  /**
   * Get image
   *
   * Retrieve an image by its ID for a specific project.
   */
  public static get<ThrowOnError extends boolean = false>(options: Options<Get2Data, ThrowOnError>) {
    return (options.client ?? client).get<Get2Responses, Get2Errors, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/images/{imageId}",
      ...options,
    });
  }

  /**
   * Upload: Mark as complete
   *
   * Complete the upload process and create the image record using API key authentication
   */
  public static uploadComplete<ThrowOnError extends boolean = false>(options: Options<UploadCompleteData, ThrowOnError>) {
    return (options.client ?? client).post<UploadCompleteResponses, UploadCompleteErrors, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/images/upload/complete",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Upload: Init
   *
   * Initialize a presigned URL upload for an image file using API key authentication
   */
  public static uploadInit<ThrowOnError extends boolean = false>(options: Options<UploadInitData, ThrowOnError>) {
    return (options.client ?? client).post<UploadInitResponses, UploadInitErrors, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/images/upload/init",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Videos {
  /**
   * List videos for a project
   *
   * Retrieve all videos for a specific project, with pagination and sorting.
   */
  public static list<ThrowOnError extends boolean = false>(options?: Options<List3Data, ThrowOnError>) {
    return (options?.client ?? client).get<List3Responses, List3Errors, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos",
      ...options,
    });
  }

  /**
   * Get a video
   *
   * Retrieve a video by its ID for a specific project.
   */
  public static get<ThrowOnError extends boolean = false>(options: Options<Get3Data, ThrowOnError>) {
    return (options.client ?? client).get<Get3Responses, Get3Errors, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}",
      ...options,
    });
  }

  /**
   * Delete all audio tracks
   *
   * Remove all additional audio tracks from a video using API key authentication
   */
  public static deleteAudioTracks<ThrowOnError extends boolean = false>(options: Options<DeleteAudioTracksData, ThrowOnError>) {
    return (options.client ?? client).delete<DeleteAudioTracksResponses, unknown, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}/audio-tracks",
      ...options,
    });
  }

  /**
   * Bulk upsert video audio tracks
   *
   * Replace all audio tracks with the provided ones using API key authentication
   */
  public static replaceAudioTracks<ThrowOnError extends boolean = false>(options: Options<ReplaceAudioTracksData, ThrowOnError>) {
    return (options.client ?? client).post<ReplaceAudioTracksResponses, unknown, ThrowOnError>({
      ...formDataBodySerializer,
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}/audio-tracks",
      ...options,
      headers: {
        "Content-Type": null,
        ...options.headers,
      },
    });
  }

  /**
   * Delete audio track
   *
   * Remove an additional audio track from a video using API key authentication
   */
  public static deleteAudioTrack<ThrowOnError extends boolean = false>(options: Options<DeleteAudioTrackData, ThrowOnError>) {
    return (options.client ?? client).delete<DeleteAudioTrackResponses, DeleteAudioTrackErrors, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}/audio-tracks/{trackId}",
      ...options,
    });
  }

  /**
   * Delete audio track by language
   *
   * Remove an audio track for a specific language using API key authentication
   */
  public static deleteAudioTrackByLanguage<ThrowOnError extends boolean = false>(
    options: Options<DeleteAudioTrackByLanguageData, ThrowOnError>
  ) {
    return (options.client ?? client).delete<DeleteAudioTrackByLanguageResponses, unknown, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}/audio-tracks/language/{lang_code}",
      ...options,
    });
  }

  /**
   * Upsert video audio track
   *
   * Add or replace an audio track for a specific language using API key authentication
   */
  public static updateAudioTrackByLanguage<ThrowOnError extends boolean = false>(
    options: Options<UpdateAudioTrackByLanguageData, ThrowOnError>
  ) {
    return (options.client ?? client).put<UpdateAudioTrackByLanguageResponses, unknown, ThrowOnError>({
      ...formDataBodySerializer,
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}/audio-tracks/language/{lang_code}",
      ...options,
      headers: {
        "Content-Type": null,
        ...options.headers,
      },
    });
  }

  /**
   * Delete video chapters
   *
   * Remove all chapters from a video using API key authentication
   */
  public static deleteChapters<ThrowOnError extends boolean = false>(options: Options<DeleteChaptersData, ThrowOnError>) {
    return (options.client ?? client).delete<DeleteChaptersResponses, DeleteChaptersErrors, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}/chapters",
      ...options,
    });
  }

  /**
   * Update video chapters
   *
   * Replace all chapters for a video (atomic PUT operation) using API key authentication
   */
  public static updateChapters<ThrowOnError extends boolean = false>(options: Options<UpdateChaptersData, ThrowOnError>) {
    return (options.client ?? client).put<UpdateChaptersResponses, UpdateChaptersErrors, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}/chapters",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete video
   *
   * Delete a video by its ID within a project
   */
  public static delete<ThrowOnError extends boolean = false>(options: Options<Delete2Data, ThrowOnError>) {
    return (options.client ?? client).delete<Delete2Responses, Delete2Errors, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}/delete",
      ...options,
    });
  }

  /**
   * Delete all subtitles
   *
   * Remove all subtitles from a video using API key authentication
   */
  public static deleteSubtitles<ThrowOnError extends boolean = false>(options: Options<DeleteSubtitlesData, ThrowOnError>) {
    return (options.client ?? client).delete<DeleteSubtitlesResponses, unknown, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}/subtitles",
      ...options,
    });
  }

  /**
   * Bulk upsert video subtitles
   *
   * Replace all subtitles with the provided ones using API key authentication
   */
  public static replaceSubtitles<ThrowOnError extends boolean = false>(options: Options<ReplaceSubtitlesData, ThrowOnError>) {
    return (options.client ?? client).post<ReplaceSubtitlesResponses, unknown, ThrowOnError>({
      ...formDataBodySerializer,
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}/subtitles",
      ...options,
      headers: {
        "Content-Type": null,
        ...options.headers,
      },
    });
  }

  /**
   * Delete subtitle
   *
   * Remove a subtitle from a video using API key authentication
   */
  public static deleteSubtitle<ThrowOnError extends boolean = false>(options: Options<DeleteSubtitleData, ThrowOnError>) {
    return (options.client ?? client).delete<DeleteSubtitleResponses, DeleteSubtitleErrors, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}/subtitles/{subtitleId}",
      ...options,
    });
  }

  /**
   * Delete subtitle by language
   *
   * Remove a subtitle for a specific language using API key authentication
   */
  public static deleteSubtitleByLanguage<ThrowOnError extends boolean = false>(
    options: Options<DeleteSubtitleByLanguageData, ThrowOnError>
  ) {
    return (options.client ?? client).delete<DeleteSubtitleByLanguageResponses, unknown, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}/subtitles/language/{lang_code}",
      ...options,
    });
  }

  /**
   * Upsert video subtitle
   *
   * Add or replace a subtitle for a specific language using API key authentication
   */
  public static updateSubtitleByLanguage<ThrowOnError extends boolean = false>(
    options: Options<UpdateSubtitleByLanguageData, ThrowOnError>
  ) {
    return (options.client ?? client).put<UpdateSubtitleByLanguageResponses, unknown, ThrowOnError>({
      ...formDataBodySerializer,
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}/subtitles/language/{lang_code}",
      ...options,
      headers: {
        "Content-Type": null,
        ...options.headers,
      },
    });
  }

  /**
   * Update video thumbnail
   *
   * Update the thumbnail image for an existing video using API key authentication
   */
  public static updateThumbnail<ThrowOnError extends boolean = false>(options: Options<UpdateThumbnailData, ThrowOnError>) {
    return (options.client ?? client).put<UpdateThumbnailResponses, UpdateThumbnailErrors, ThrowOnError>({
      ...formDataBodySerializer,
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/{videoId}/thumbnail",
      ...options,
      headers: {
        "Content-Type": null,
        ...options.headers,
      },
    });
  }

  /**
   * List available subtitle languages
   *
   * Get list of supported languages for subtitles
   */
  public static listLanguages<ThrowOnError extends boolean = false>(options?: Options<ListLanguagesData, ThrowOnError>) {
    return (options?.client ?? client).get<ListLanguagesResponses, unknown, ThrowOnError>({url: "/videos/languages", ...options});
  }

  /**
   * Upload: Mark as complete
   *
   * Mark a video upload as complete after successful upload to storage using API key authentication
   */
  public static uploadComplete<ThrowOnError extends boolean = false>(options: Options<UploadComplete2Data, ThrowOnError>) {
    return (options.client ?? client).post<UploadComplete2Responses, UploadComplete2Errors, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/upload/complete",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Upload: Init
   *
   * Initialize a video upload and get presigned URLs for video and poster using API key authentication
   */
  public static uploadInit<ThrowOnError extends boolean = false>(options: Options<UploadInit2Data, ThrowOnError>) {
    return (options.client ?? client).post<UploadInit2Responses, UploadInit2Errors, ThrowOnError>({
      security: [{name: "X-API-Key", type: "apiKey"}],
      url: "/videos/upload/init",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}
