// This file is auto-generated by @hey-api/openapi-ts

import {type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer} from "./client";
import {client} from "./client.gen";
import type {
  DeleteImagesByImageIdData,
  DeleteImagesByImageIdErrors,
  DeleteImagesByImageIdResponses,
  DeleteVideosByVideoIdAudioTracksByLangCodeData,
  DeleteVideosByVideoIdAudioTracksByLangCodeResponses,
  DeleteVideosByVideoIdAudioTracksByTrackIdData,
  DeleteVideosByVideoIdAudioTracksByTrackIdErrors,
  DeleteVideosByVideoIdAudioTracksByTrackIdResponses,
  DeleteVideosByVideoIdAudioTracksData,
  DeleteVideosByVideoIdAudioTracksResponses,
  DeleteVideosByVideoIdChaptersData,
  DeleteVideosByVideoIdChaptersErrors,
  DeleteVideosByVideoIdChaptersResponses,
  DeleteVideosByVideoIdDeleteData,
  DeleteVideosByVideoIdDeleteErrors,
  DeleteVideosByVideoIdDeleteResponses,
  DeleteVideosByVideoIdSubtitlesByLangCodeData,
  DeleteVideosByVideoIdSubtitlesByLangCodeResponses,
  DeleteVideosByVideoIdSubtitlesBySubtitleIdData,
  DeleteVideosByVideoIdSubtitlesBySubtitleIdErrors,
  DeleteVideosByVideoIdSubtitlesBySubtitleIdResponses,
  DeleteVideosByVideoIdSubtitlesData,
  DeleteVideosByVideoIdSubtitlesResponses,
  GetFeedsByFeedIdByPostIdData,
  GetFeedsByFeedIdByPostIdErrors,
  GetFeedsByFeedIdByPostIdResponses,
  GetFeedsByFeedIdCreatorsByCreatorIdData,
  GetFeedsByFeedIdCreatorsByCreatorIdErrors,
  GetFeedsByFeedIdCreatorsByCreatorIdResponses,
  GetFeedsByFeedIdData,
  GetFeedsByFeedIdErrors,
  GetFeedsByFeedIdResponses,
  GetImagesByImageIdData,
  GetImagesByImageIdErrors,
  GetImagesByImageIdResponses,
  GetImagesData,
  GetImagesErrors,
  GetImagesResponses,
  GetVideosByVideoIdData,
  GetVideosByVideoIdErrors,
  GetVideosByVideoIdResponses,
  GetVideosData,
  GetVideosErrors,
  GetVideosLanguagesData,
  GetVideosLanguagesResponses,
  GetVideosResponses,
  PostImagesUploadCompleteData,
  PostImagesUploadCompleteErrors,
  PostImagesUploadCompleteResponses,
  PostImagesUploadInitData,
  PostImagesUploadInitErrors,
  PostImagesUploadInitResponses,
  PostVideosByVideoIdAudioTracksData,
  PostVideosByVideoIdAudioTracksResponses,
  PostVideosByVideoIdSubtitlesData,
  PostVideosByVideoIdSubtitlesResponses,
  PostVideosUploadCompleteData,
  PostVideosUploadCompleteErrors,
  PostVideosUploadCompleteResponses,
  PostVideosUploadInitData,
  PostVideosUploadInitErrors,
  PostVideosUploadInitResponses,
  PutVideosByVideoIdAudioTracksByLangCodeData,
  PutVideosByVideoIdAudioTracksByLangCodeResponses,
  PutVideosByVideoIdChaptersData,
  PutVideosByVideoIdChaptersErrors,
  PutVideosByVideoIdChaptersResponses,
  PutVideosByVideoIdSubtitlesByLangCodeData,
  PutVideosByVideoIdSubtitlesByLangCodeResponses,
  PutVideosByVideoIdThumbnailData,
  PutVideosByVideoIdThumbnailErrors,
  PutVideosByVideoIdThumbnailResponses,
} from "./types.gen";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<
  TData,
  ThrowOnError,
  TResponse
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List posts in a feed
 *
 * Retrieve posts in a feed, with pagination.
 */
export const getFeedsByFeedId = <ThrowOnError extends boolean = false>(options: Options<GetFeedsByFeedIdData, ThrowOnError>) =>
  (options.client ?? client).get<GetFeedsByFeedIdResponses, GetFeedsByFeedIdErrors, ThrowOnError>({url: "/feeds/{feedId}", ...options});

/**
 * Get a post
 *
 * Retrieve a post from feed by its ID
 */
export const getFeedsByFeedIdByPostId = <ThrowOnError extends boolean = false>(
  options: Options<GetFeedsByFeedIdByPostIdData, ThrowOnError>
) =>
  (options.client ?? client).get<GetFeedsByFeedIdByPostIdResponses, GetFeedsByFeedIdByPostIdErrors, ThrowOnError>({
    url: "/feeds/{feedId}/{postId}",
    ...options,
  });

/**
 * List posts by creator
 *
 * Retrieve posts in a feed by a specific creator, with pagination.
 */
export const getFeedsByFeedIdCreatorsByCreatorId = <ThrowOnError extends boolean = false>(
  options: Options<GetFeedsByFeedIdCreatorsByCreatorIdData, ThrowOnError>
) =>
  (options.client ?? client).get<GetFeedsByFeedIdCreatorsByCreatorIdResponses, GetFeedsByFeedIdCreatorsByCreatorIdErrors, ThrowOnError>({
    url: "/feeds/{feedId}/creators/{creatorId}",
    ...options,
  });

/**
 * List images for a project
 *
 * Retrieve all images for a specific project, with pagination and sorting.
 */
export const getImages = <ThrowOnError extends boolean = false>(options?: Options<GetImagesData, ThrowOnError>) =>
  (options?.client ?? client).get<GetImagesResponses, GetImagesErrors, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/images",
    ...options,
  });

/**
 * Delete image
 *
 * delete an image by marking it as deleted
 */
export const deleteImagesByImageId = <ThrowOnError extends boolean = false>(options: Options<DeleteImagesByImageIdData, ThrowOnError>) =>
  (options.client ?? client).delete<DeleteImagesByImageIdResponses, DeleteImagesByImageIdErrors, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/images/{imageId}",
    ...options,
  });

/**
 * Get image
 *
 * Retrieve an image by its ID for a specific project.
 */
export const getImagesByImageId = <ThrowOnError extends boolean = false>(options: Options<GetImagesByImageIdData, ThrowOnError>) =>
  (options.client ?? client).get<GetImagesByImageIdResponses, GetImagesByImageIdErrors, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/images/{imageId}",
    ...options,
  });

/**
 * Upload: Mark as complete
 *
 * Complete the upload process and create the image record using API key authentication
 */
export const postImagesUploadComplete = <ThrowOnError extends boolean = false>(
  options: Options<PostImagesUploadCompleteData, ThrowOnError>
) =>
  (options.client ?? client).post<PostImagesUploadCompleteResponses, PostImagesUploadCompleteErrors, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/images/upload/complete",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Upload: Init
 *
 * Initialize a presigned URL upload for an image file using API key authentication
 */
export const postImagesUploadInit = <ThrowOnError extends boolean = false>(options: Options<PostImagesUploadInitData, ThrowOnError>) =>
  (options.client ?? client).post<PostImagesUploadInitResponses, PostImagesUploadInitErrors, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/images/upload/init",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List videos for a project
 *
 * Retrieve all videos for a specific project, with pagination and sorting.
 */
export const getVideos = <ThrowOnError extends boolean = false>(options?: Options<GetVideosData, ThrowOnError>) =>
  (options?.client ?? client).get<GetVideosResponses, GetVideosErrors, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos",
    ...options,
  });

/**
 * Get a video
 *
 * Retrieve a video by its ID for a specific project.
 */
export const getVideosByVideoId = <ThrowOnError extends boolean = false>(options: Options<GetVideosByVideoIdData, ThrowOnError>) =>
  (options.client ?? client).get<GetVideosByVideoIdResponses, GetVideosByVideoIdErrors, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/{videoId}",
    ...options,
  });

/**
 * Delete all audio tracks
 *
 * Remove all additional audio tracks from a video using API key authentication
 */
export const deleteVideosByVideoIdAudioTracks = <ThrowOnError extends boolean = false>(
  options: Options<DeleteVideosByVideoIdAudioTracksData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteVideosByVideoIdAudioTracksResponses, unknown, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/{videoId}/audio-tracks",
    ...options,
  });

/**
 * Bulk upsert video audio tracks
 *
 * Replace all audio tracks with the provided ones using API key authentication
 */
export const postVideosByVideoIdAudioTracks = <ThrowOnError extends boolean = false>(
  options: Options<PostVideosByVideoIdAudioTracksData, ThrowOnError>
) =>
  (options.client ?? client).post<PostVideosByVideoIdAudioTracksResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/{videoId}/audio-tracks",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Delete audio track by language
 *
 * Remove an audio track for a specific language using API key authentication
 */
export const deleteVideosByVideoIdAudioTracksByLangCode = <ThrowOnError extends boolean = false>(
  options: Options<DeleteVideosByVideoIdAudioTracksByLangCodeData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteVideosByVideoIdAudioTracksByLangCodeResponses, unknown, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/{videoId}/audio-tracks/{lang_code}",
    ...options,
  });

/**
 * Upsert video audio track
 *
 * Add or replace an audio track for a specific language using API key authentication
 */
export const putVideosByVideoIdAudioTracksByLangCode = <ThrowOnError extends boolean = false>(
  options: Options<PutVideosByVideoIdAudioTracksByLangCodeData, ThrowOnError>
) =>
  (options.client ?? client).put<PutVideosByVideoIdAudioTracksByLangCodeResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/{videoId}/audio-tracks/{lang_code}",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Delete audio track
 *
 * Remove an additional audio track from a video using API key authentication
 */
export const deleteVideosByVideoIdAudioTracksByTrackId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteVideosByVideoIdAudioTracksByTrackIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteVideosByVideoIdAudioTracksByTrackIdResponses,
    DeleteVideosByVideoIdAudioTracksByTrackIdErrors,
    ThrowOnError
  >({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/{videoId}/audio-tracks/{trackId}",
    ...options,
  });

/**
 * Delete video chapters
 *
 * Remove all chapters from a video using API key authentication
 */
export const deleteVideosByVideoIdChapters = <ThrowOnError extends boolean = false>(
  options: Options<DeleteVideosByVideoIdChaptersData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteVideosByVideoIdChaptersResponses, DeleteVideosByVideoIdChaptersErrors, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/{videoId}/chapters",
    ...options,
  });

/**
 * Update video chapters
 *
 * Replace all chapters for a video (atomic PUT operation) using API key authentication
 */
export const putVideosByVideoIdChapters = <ThrowOnError extends boolean = false>(
  options: Options<PutVideosByVideoIdChaptersData, ThrowOnError>
) =>
  (options.client ?? client).put<PutVideosByVideoIdChaptersResponses, PutVideosByVideoIdChaptersErrors, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/{videoId}/chapters",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete video
 *
 * Delete a video by its ID within a project
 */
export const deleteVideosByVideoIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteVideosByVideoIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteVideosByVideoIdDeleteResponses, DeleteVideosByVideoIdDeleteErrors, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/{videoId}/delete",
    ...options,
  });

/**
 * Delete all subtitles
 *
 * Remove all subtitles from a video using API key authentication
 */
export const deleteVideosByVideoIdSubtitles = <ThrowOnError extends boolean = false>(
  options: Options<DeleteVideosByVideoIdSubtitlesData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteVideosByVideoIdSubtitlesResponses, unknown, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/{videoId}/subtitles",
    ...options,
  });

/**
 * Bulk upsert video subtitles
 *
 * Replace all subtitles with the provided ones using API key authentication
 */
export const postVideosByVideoIdSubtitles = <ThrowOnError extends boolean = false>(
  options: Options<PostVideosByVideoIdSubtitlesData, ThrowOnError>
) =>
  (options.client ?? client).post<PostVideosByVideoIdSubtitlesResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/{videoId}/subtitles",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Delete subtitle by language
 *
 * Remove a subtitle for a specific language using API key authentication
 */
export const deleteVideosByVideoIdSubtitlesByLangCode = <ThrowOnError extends boolean = false>(
  options: Options<DeleteVideosByVideoIdSubtitlesByLangCodeData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteVideosByVideoIdSubtitlesByLangCodeResponses, unknown, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/{videoId}/subtitles/{lang_code}",
    ...options,
  });

/**
 * Upsert video subtitle
 *
 * Add or replace a subtitle for a specific language using API key authentication
 */
export const putVideosByVideoIdSubtitlesByLangCode = <ThrowOnError extends boolean = false>(
  options: Options<PutVideosByVideoIdSubtitlesByLangCodeData, ThrowOnError>
) =>
  (options.client ?? client).put<PutVideosByVideoIdSubtitlesByLangCodeResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/{videoId}/subtitles/{lang_code}",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Delete subtitle
 *
 * Remove a subtitle from a video using API key authentication
 */
export const deleteVideosByVideoIdSubtitlesBySubtitleId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteVideosByVideoIdSubtitlesBySubtitleIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteVideosByVideoIdSubtitlesBySubtitleIdResponses,
    DeleteVideosByVideoIdSubtitlesBySubtitleIdErrors,
    ThrowOnError
  >({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/{videoId}/subtitles/{subtitleId}",
    ...options,
  });

/**
 * Update video thumbnail
 *
 * Update the thumbnail image for an existing video
 */
export const putVideosByVideoIdThumbnail = <ThrowOnError extends boolean = false>(
  options: Options<PutVideosByVideoIdThumbnailData, ThrowOnError>
) =>
  (options.client ?? client).put<PutVideosByVideoIdThumbnailResponses, PutVideosByVideoIdThumbnailErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    security: [{name: "Authorization", type: "apiKey"}],
    url: "/videos/{videoId}/thumbnail",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * List available subtitle languages
 *
 * Get list of supported languages for subtitles
 */
export const getVideosLanguages = <ThrowOnError extends boolean = false>(options?: Options<GetVideosLanguagesData, ThrowOnError>) =>
  (options?.client ?? client).get<GetVideosLanguagesResponses, unknown, ThrowOnError>({url: "/videos/languages", ...options});

/**
 * Upload: Mark as complete
 *
 * Mark a video upload as complete after successful upload to storage using API key authentication
 */
export const postVideosUploadComplete = <ThrowOnError extends boolean = false>(
  options: Options<PostVideosUploadCompleteData, ThrowOnError>
) =>
  (options.client ?? client).post<PostVideosUploadCompleteResponses, PostVideosUploadCompleteErrors, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/upload/complete",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Upload: Init
 *
 * Initialize a video upload and get presigned URLs for video and poster using API key authentication
 */
export const postVideosUploadInit = <ThrowOnError extends boolean = false>(options: Options<PostVideosUploadInitData, ThrowOnError>) =>
  (options.client ?? client).post<PostVideosUploadInitResponses, PostVideosUploadInitErrors, ThrowOnError>({
    security: [{name: "X-API-Key", type: "apiKey"}],
    url: "/videos/upload/init",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
