// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.rixl.com/" | (string & {});
};

export type AudioTrack = {
  created_at?: string;
  format?: string;
  id?: string;
  label?: string;
  language_code?: string;
  name?: string;
  size?: number;
  url?: string;
  video_id?: string;
};

export type AudioTrackDelete = {
  message?: string;
  status?: string;
};

export type Chapter = {
  duration_label?: string;
  end_time_sec?: number;
  start_time_sec?: number;
  title?: string;
};

export type File = {
  created_at?: string;
  format?: string;
  id?: string;
  name?: string;
  project_id?: string;
  size?: number;
  status?: FileStatus;
  updated_at?: string;
  url?: string;
};

export type FileStatus = "uploading" | "uploaded" | "processing" | "preparing" | "ready" | "error";

export type Image = {
  attached_to_video?: boolean;
  file?: File;
  height?: number;
  id?: string;
  thumbhash?: string;
  width?: number;
};

export type Post = {
  created_at?: string;
  creator_id?: string;
  description?: string;
  feed_id?: string;
  id?: string;
  image?: Image;
  plan_type?: GithubComRixlhqApiDbSqlcPlanType;
  type?: PostType;
  updated_at?: string;
  video?: GithubComRixlhqApiInternalVideosVideoResponse;
};

export type PostType = "image" | "video";

export type Subtitle = {
  created_at?: string;
  id?: string;
  label?: string;
  language_code?: string;
  name?: string;
  size?: number;
  url?: string;
  video_id?: string;
};

export type SubtitleDelete = {
  message?: string;
  status?: string;
};

export type UpdateChaptersRequest = {
  chapters?: Array<GithubComRixlhqApiInternalVideosTypesChapterInput>;
};

export type UpdateChaptersResponse = {
  chapters?: Array<Chapter>;
  video_id?: string;
};

export type Video = {
  bitrate?: number;
  chapters?: Array<Chapter>;
  codec?: string;
  duration?: number;
  file?: File;
  framerate?: string;
  hdr?: boolean;
  height?: number;
  id?: string;
  plan_type?: GithubComRixlhqApiDbSqlcPlanType;
  poster?: Image;
  width?: number;
};

export type VideoUploadInitRequest = {
  file_name: string;
  image_format?: string;
  video_quality?: GithubComRixlhqApiDbSqlcVideoQuality;
};

export type GithubComRixlhqApiDbSqlcPlanType = "free" | "pro" | "custom" | "pay_as_you_go";

export type GithubComRixlhqApiDbSqlcVideoQuality = "basic" | "shorts" | "pro";

/**
 * Standard error response returned by the API
 */
export type GithubComRixlhqApiInternalErrorsErrorResponse = {
  /**
   * HTTP status code
   */
  code?: number;
  /**
   * Optional details about the error
   */
  details?: string;
  /**
   * Error message describing what went wrong
   */
  error?: string;
};

export type GithubComRixlhqApiInternalVideosVideoResponse = {
  bitrate?: number;
  chapters?: Array<Chapter>;
  codec?: string;
  duration?: number;
  file?: File;
  framerate?: string;
  hdr?: boolean;
  height?: number;
  id?: string;
  plan_type?: GithubComRixlhqApiDbSqlcPlanType;
  poster?: Image;
  width?: number;
};

export type GithubComRixlhqApiInternalVideosHandlerUploadCompleteRequest = {
  video_id?: string;
};

export type GithubComRixlhqApiInternalVideosHandlerUploadInitResponse = {
  poster_id?: string;
  poster_presigned_url?: string;
  upload_expires?: number;
  video_id?: string;
  video_presigned_url?: string;
};

export type GithubComRixlhqApiInternalVideosTypesChapterInput = {
  start_time_sec?: number;
  title?: string;
};

export type InternalImagesHandlerCompleteRequest = {
  attached_to_video?: boolean;
  image_id?: string;
};

export type InternalImagesHandlerInitResponse = {
  image_id?: string;
  presigned_url?: string;
  upload_expires?: number;
};

export type InternalImagesHandlerUploadInitRequest = {
  format?: string;
  name?: string;
};

export type InternalVideosHandlerSubtitlesLanguageResponse = {
  code?: string;
  name?: string;
};

export type PaginationPaginatedResponseImage = {
  /**
   * Data contains the slice of items for the current request.
   */
  data?: Array<Image>;
  /**
   * Pagination data for the request.
   */
  pagination?: PaginationPagination;
};

export type PaginationPaginatedResponsePost = {
  /**
   * Data contains the slice of items for the current request.
   */
  data?: Array<Post>;
  /**
   * Pagination data for the request.
   */
  pagination?: PaginationPagination;
};

export type PaginationPaginatedResponseVideo = {
  /**
   * Data contains the slice of items for the current request.
   */
  data?: Array<Video>;
  /**
   * Pagination data for the request.
   */
  pagination?: PaginationPagination;
};

export type PaginationPagination = {
  /**
   * Maximum number of items to return in a single request.
   */
  limit?: number;
  /**
   * Starting point of the result set.
   */
  offset?: number;
  /**
   * The total number of available items in the full list.
   */
  total?: number;
};

export type ListData = {
  body?: never;
  path: {
    /**
     * Feed ID
     */
    feedId: string;
  };
  query?: {
    /**
     * Maximum number of items to return in a single request. <br> **Default:** `25`
     */
    limit?: number;
    /**
     * Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
     */
    offset?: number;
  };
  url: "/feeds/{feedId}";
};

export type ListErrors = {
  /**
   * Invalid feed ID or query parameters
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal server error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type ListError = ListErrors[keyof ListErrors];

export type ListResponses = {
  /**
   * OK
   */
  200: PaginationPaginatedResponsePost;
};

export type ListResponse = ListResponses[keyof ListResponses];

export type GetData = {
  body?: never;
  path: {
    /**
     * Feed ID
     */
    feedId: string;
    /**
     * Post ID
     */
    postId: string;
  };
  query?: never;
  url: "/feeds/{feedId}/{postId}";
};

export type GetErrors = {
  /**
   * Bad Request
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Not Found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type GetError = GetErrors[keyof GetErrors];

export type GetResponses = {
  /**
   * OK
   */
  200: Post;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type ListByCreatorData = {
  body?: never;
  path: {
    /**
     * Feed ID
     */
    feedId: string;
    /**
     * Creator ID
     */
    creatorId: string;
  };
  query?: {
    /**
     * Maximum number of items to return in a single request. <br> **Default:** `25`
     */
    limit?: number;
    /**
     * Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
     */
    offset?: number;
  };
  url: "/feeds/{feedId}/creators/{creatorId}";
};

export type ListByCreatorErrors = {
  /**
   * Invalid feed ID, creator ID, or query parameters
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal server error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type ListByCreatorError = ListByCreatorErrors[keyof ListByCreatorErrors];

export type ListByCreatorResponses = {
  /**
   * OK
   */
  200: PaginationPaginatedResponsePost;
};

export type ListByCreatorResponse = ListByCreatorResponses[keyof ListByCreatorResponses];

export type List2Data = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of items to return in a single request. <br> **Default:** `25`
     */
    limit?: number;
    /**
     * Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
     */
    offset?: number;
    /**
     * Field to sort by (created_at, name, size, updated_at)
     */
    sort?: string;
    /**
     * Sort order (asc, desc)
     */
    order?: string;
  };
  url: "/images";
};

export type List2Errors = {
  /**
   * Invalid query parameters
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Forbidden
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal server error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type List2Error = List2Errors[keyof List2Errors];

export type List2Responses = {
  /**
   * OK
   */
  200: PaginationPaginatedResponseImage;
};

export type List2Response = List2Responses[keyof List2Responses];

export type DeleteData = {
  body?: never;
  path: {
    /**
     * Image ID
     */
    imageId: string;
  };
  query?: never;
  url: "/images/{imageId}";
};

export type DeleteErrors = {
  /**
   * Invalid project ID or image ID
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Image not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to delete image
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type DeleteError = DeleteErrors[keyof DeleteErrors];

export type DeleteResponses = {
  /**
   * Image deleted successfully
   */
  204: void;
};

export type DeleteResponse = DeleteResponses[keyof DeleteResponses];

export type Get2Data = {
  body?: never;
  path: {
    /**
     * Image ID
     */
    imageId: string;
  };
  query?: never;
  url: "/images/{imageId}";
};

export type Get2Errors = {
  /**
   * Invalid image ID
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Forbidden
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Image not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal server error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type Get2Error = Get2Errors[keyof Get2Errors];

export type Get2Responses = {
  /**
   * OK
   */
  200: Image;
};

export type Get2Response = Get2Responses[keyof Get2Responses];

export type UploadCompleteData = {
  /**
   * Upload completion request
   */
  body: InternalImagesHandlerCompleteRequest;
  path?: never;
  query?: never;
  url: "/images/upload/complete";
};

export type UploadCompleteErrors = {
  /**
   * Invalid request body
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized - Invalid API key
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * File not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to complete upload or create image
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type UploadCompleteError = UploadCompleteErrors[keyof UploadCompleteErrors];

export type UploadCompleteResponses = {
  /**
   * OK
   */
  200: Image;
};

export type UploadCompleteResponse = UploadCompleteResponses[keyof UploadCompleteResponses];

export type UploadInitData = {
  /**
   * Upload initialization request
   */
  body: InternalImagesHandlerUploadInitRequest;
  path?: never;
  query?: never;
  url: "/images/upload/init";
};

export type UploadInitErrors = {
  /**
   * Invalid request body
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized - Invalid API key
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to initialize upload
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type UploadInitError = UploadInitErrors[keyof UploadInitErrors];

export type UploadInitResponses = {
  /**
   * OK
   */
  200: InternalImagesHandlerInitResponse;
};

export type UploadInitResponse = UploadInitResponses[keyof UploadInitResponses];

export type List3Data = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of items to return in a single request. <br> **Default:** `25`
     */
    limit?: number;
    /**
     * Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
     */
    offset?: number;
    /**
     * Field to sort by (created_at, name, size, updated_at, duration)
     */
    sort?: string;
    /**
     * Sort order (asc, desc)
     */
    order?: string;
  };
  url: "/videos";
};

export type List3Errors = {
  /**
   * Invalid query parameters
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Forbidden
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal server error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type List3Error = List3Errors[keyof List3Errors];

export type List3Responses = {
  /**
   * OK
   */
  200: PaginationPaginatedResponseVideo;
};

export type List3Response = List3Responses[keyof List3Responses];

export type Get3Data = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}";
};

export type Get3Errors = {
  /**
   * Invalid video ID
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Forbidden
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Video not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal server error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type Get3Error = Get3Errors[keyof Get3Errors];

export type Get3Responses = {
  /**
   * OK
   */
  200: Video;
};

export type Get3Response = Get3Responses[keyof Get3Responses];

export type DeleteAudioTracksData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/audio-tracks";
};

export type DeleteAudioTracksResponses = {
  /**
   * OK
   */
  200: AudioTrackDelete;
};

export type DeleteAudioTracksResponse = DeleteAudioTracksResponses[keyof DeleteAudioTracksResponses];

export type ReplaceAudioTracksData = {
  /**
   * Audio files (.mp3, .opus, .flac, .wav, .ac3, .m4a, .aac) | Comma-separated language codes | Comma-separated labels
   */
  body: {
    /**
     * Audio files (.mp3, .opus, .flac, .wav, .ac3, .m4a, .aac)
     */
    files: Array<Blob | File>;
    /**
     * Comma-separated labels
     */
    labels: string;
    /**
     * Comma-separated language codes
     */
    language_codes: string;
  };
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/audio-tracks";
};

export type ReplaceAudioTracksResponses = {
  /**
   * OK
   */
  200: Array<AudioTrack>;
};

export type ReplaceAudioTracksResponse = ReplaceAudioTracksResponses[keyof ReplaceAudioTracksResponses];

export type DeleteAudioTrackData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
    /**
     * Audio Track ID
     */
    trackId: string;
  };
  query?: never;
  url: "/videos/{videoId}/audio-tracks/{trackId}";
};

export type DeleteAudioTrackErrors = {
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Forbidden
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Not Found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal Server Error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type DeleteAudioTrackError = DeleteAudioTrackErrors[keyof DeleteAudioTrackErrors];

export type DeleteAudioTrackResponses = {
  /**
   * OK
   */
  200: AudioTrackDelete;
};

export type DeleteAudioTrackResponse = DeleteAudioTrackResponses[keyof DeleteAudioTrackResponses];

export type DeleteAudioTrackByLanguageData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
    /**
     * Language Code (BCP 47)
     */
    lang_code: string;
  };
  query?: never;
  url: "/videos/{videoId}/audio-tracks/language/{lang_code}";
};

export type DeleteAudioTrackByLanguageResponses = {
  /**
   * OK
   */
  200: AudioTrackDelete;
};

export type DeleteAudioTrackByLanguageResponse = DeleteAudioTrackByLanguageResponses[keyof DeleteAudioTrackByLanguageResponses];

export type UpdateAudioTrackByLanguageData = {
  /**
   * Audio file (.mp3, .opus, .flac, .wav, .ac3, .m4a, .aac) | Label (e.g. English)
   */
  body: {
    /**
     * Audio file (.mp3, .opus, .flac, .wav, .ac3, .m4a, .aac)
     */
    file: Blob | File;
    /**
     * Label (e.g. English)
     */
    label?: string;
  };
  path: {
    /**
     * Video ID
     */
    videoId: string;
    /**
     * Language Code (BCP 47)
     */
    lang_code: string;
  };
  query?: never;
  url: "/videos/{videoId}/audio-tracks/language/{lang_code}";
};

export type UpdateAudioTrackByLanguageResponses = {
  /**
   * OK
   */
  200: AudioTrack;
};

export type UpdateAudioTrackByLanguageResponse = UpdateAudioTrackByLanguageResponses[keyof UpdateAudioTrackByLanguageResponses];

export type DeleteChaptersData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/chapters";
};

export type DeleteChaptersErrors = {
  /**
   * Unauthorized - Invalid API key
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Video not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to delete chapters
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type DeleteChaptersError = DeleteChaptersErrors[keyof DeleteChaptersErrors];

export type DeleteChaptersResponses = {
  /**
   * OK
   */
  200: UpdateChaptersResponse;
};

export type DeleteChaptersResponse = DeleteChaptersResponses[keyof DeleteChaptersResponses];

export type UpdateChaptersData = {
  /**
   * Chapters array
   */
  body: UpdateChaptersRequest;
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/chapters";
};

export type UpdateChaptersErrors = {
  /**
   * Invalid request body or video duration not available
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized - Invalid API key
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Video not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to update chapters
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type UpdateChaptersError = UpdateChaptersErrors[keyof UpdateChaptersErrors];

export type UpdateChaptersResponses = {
  /**
   * OK
   */
  200: UpdateChaptersResponse;
};

export type UpdateChaptersResponse2 = UpdateChaptersResponses[keyof UpdateChaptersResponses];

export type Delete2Data = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/delete";
};

export type Delete2Errors = {
  /**
   * Invalid project ID or video ID
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Video not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to delete video
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type Delete2Error = Delete2Errors[keyof Delete2Errors];

export type Delete2Responses = {
  /**
   * Video deleted successfully
   */
  204: void;
};

export type Delete2Response = Delete2Responses[keyof Delete2Responses];

export type DeleteSubtitlesData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/subtitles";
};

export type DeleteSubtitlesResponses = {
  /**
   * OK
   */
  200: SubtitleDelete;
};

export type DeleteSubtitlesResponse = DeleteSubtitlesResponses[keyof DeleteSubtitlesResponses];

export type ReplaceSubtitlesData = {
  /**
   * Subtitle files (.srt or .vtt) | Comma-separated language codes | Comma-separated labels
   */
  body: {
    /**
     * Subtitle files (.srt or .vtt)
     */
    files: Array<Blob | File>;
    /**
     * Comma-separated labels
     */
    labels: string;
    /**
     * Comma-separated language codes
     */
    language_codes: string;
  };
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/subtitles";
};

export type ReplaceSubtitlesResponses = {
  /**
   * OK
   */
  200: Array<Subtitle>;
};

export type ReplaceSubtitlesResponse = ReplaceSubtitlesResponses[keyof ReplaceSubtitlesResponses];

export type DeleteSubtitleData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
    /**
     * Subtitle ID
     */
    subtitleId: string;
  };
  query?: never;
  url: "/videos/{videoId}/subtitles/{subtitleId}";
};

export type DeleteSubtitleErrors = {
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Forbidden
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Not Found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal Server Error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type DeleteSubtitleError = DeleteSubtitleErrors[keyof DeleteSubtitleErrors];

export type DeleteSubtitleResponses = {
  /**
   * OK
   */
  200: SubtitleDelete;
};

export type DeleteSubtitleResponse = DeleteSubtitleResponses[keyof DeleteSubtitleResponses];

export type DeleteSubtitleByLanguageData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
    /**
     * Language Code (BCP 47)
     */
    lang_code: string;
  };
  query?: never;
  url: "/videos/{videoId}/subtitles/language/{lang_code}";
};

export type DeleteSubtitleByLanguageResponses = {
  /**
   * OK
   */
  200: SubtitleDelete;
};

export type DeleteSubtitleByLanguageResponse = DeleteSubtitleByLanguageResponses[keyof DeleteSubtitleByLanguageResponses];

export type UpdateSubtitleByLanguageData = {
  /**
   * Subtitle file (.srt or .vtt) | Label (e.g. English)
   */
  body: {
    /**
     * Subtitle file (.srt or .vtt)
     */
    file: Blob | File;
    /**
     * Label (e.g. English)
     */
    label?: string;
  };
  path: {
    /**
     * Video ID
     */
    videoId: string;
    /**
     * Language Code (BCP 47)
     */
    lang_code: string;
  };
  query?: never;
  url: "/videos/{videoId}/subtitles/language/{lang_code}";
};

export type UpdateSubtitleByLanguageResponses = {
  /**
   * OK
   */
  200: Subtitle;
};

export type UpdateSubtitleByLanguageResponse = UpdateSubtitleByLanguageResponses[keyof UpdateSubtitleByLanguageResponses];

export type UpdateThumbnailData = {
  /**
   * Thumbnail image file (max 5MB, image*)
   */
  body: {
    /**
     * Thumbnail image file (max 5MB, image*)
     */
    thumbnail: Blob | File;
  };
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/thumbnail";
};

export type UpdateThumbnailErrors = {
  /**
   * Invalid file or request
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized - Invalid API key
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Video not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Upload or update failed
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type UpdateThumbnailError = UpdateThumbnailErrors[keyof UpdateThumbnailErrors];

export type UpdateThumbnailResponses = {
  /**
   * Video with updated thumbnail
   */
  200: Video;
};

export type UpdateThumbnailResponse = UpdateThumbnailResponses[keyof UpdateThumbnailResponses];

export type ListLanguagesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/videos/languages";
};

export type ListLanguagesResponses = {
  /**
   * OK
   */
  200: Array<InternalVideosHandlerSubtitlesLanguageResponse>;
};

export type ListLanguagesResponse = ListLanguagesResponses[keyof ListLanguagesResponses];

export type UploadComplete2Data = {
  /**
   * Video upload completion request
   */
  body: GithubComRixlhqApiInternalVideosHandlerUploadCompleteRequest;
  path?: never;
  query?: never;
  url: "/videos/upload/complete";
};

export type UploadComplete2Errors = {
  /**
   * Invalid request body
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized - Invalid API key
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * File not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to complete upload
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type UploadComplete2Error = UploadComplete2Errors[keyof UploadComplete2Errors];

export type UploadComplete2Responses = {
  /**
   * OK
   */
  200: Video;
};

export type UploadComplete2Response = UploadComplete2Responses[keyof UploadComplete2Responses];

export type UploadInit2Data = {
  /**
   * Video upload initialization request
   */
  body: VideoUploadInitRequest;
  path?: never;
  query?: never;
  url: "/videos/upload/init";
};

export type UploadInit2Errors = {
  /**
   * Invalid request body
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized - Invalid API key
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to initialize upload
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type UploadInit2Error = UploadInit2Errors[keyof UploadInit2Errors];

export type UploadInit2Responses = {
  /**
   * OK
   */
  200: GithubComRixlhqApiInternalVideosHandlerUploadInitResponse;
};

export type UploadInit2Response = UploadInit2Responses[keyof UploadInit2Responses];
