// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.rixl.com/" | (string & {});
};

export type AudioTrack = {
  created_at?: string;
  format?: string;
  id?: string;
  label?: string;
  language_code?: string;
  name?: string;
  size?: number;
  url?: string;
  video_id?: string;
};

export type AudioTrackDelete = {
  message?: string;
  status?: string;
};

export type Chapter = {
  duration_label?: string;
  end_time_sec?: number;
  start_time_sec?: number;
  title?: string;
};

export type File = {
  created_at?: string;
  format?: string;
  id?: string;
  name?: string;
  project_id?: string;
  size?: number;
  status?: FileStatus;
  updated_at?: string;
  url?: string;
};

export type FileStatus = "uploading" | "uploaded" | "processing" | "preparing" | "ready" | "error";

export type Image = {
  attached_to_video?: boolean;
  file?: File;
  height?: number;
  id?: string;
  thumbhash?: string;
  width?: number;
};

export type Post = {
  created_at?: string;
  creator_id?: string;
  description?: string;
  feed_id?: string;
  id?: string;
  image?: Image;
  plan_type?: GithubComRixlhqApiDbSqlcPlanType;
  type?: PostType;
  updated_at?: string;
  video?: GithubComRixlhqApiInternalVideosVideoResponse;
};

export type PostType = "image" | "video";

export type Subtitle = {
  created_at?: string;
  id?: string;
  label?: string;
  language_code?: string;
  name?: string;
  size?: number;
  url?: string;
  video_id?: string;
};

export type SubtitleDelete = {
  message?: string;
  status?: string;
};

export type UpdateChaptersRequest = {
  chapters?: Array<GithubComRixlhqApiInternalVideosTypesChapterInput>;
};

export type UpdateChaptersResponse = {
  chapters?: Array<Chapter>;
  video_id?: string;
};

export type Video = {
  bitrate?: number;
  chapters?: Array<Chapter>;
  codec?: string;
  duration?: number;
  file?: File;
  framerate?: string;
  hdr?: boolean;
  height?: number;
  id?: string;
  plan_type?: GithubComRixlhqApiDbSqlcPlanType;
  poster?: Image;
  width?: number;
};

export type VideoUploadInitRequest = {
  file_name: string;
  image_format?: string;
  video_quality?: GithubComRixlhqApiDbSqlcVideoQuality;
};

export type GithubComRixlhqApiDbSqlcPlanType = "free" | "pro" | "custom" | "pay_as_you_go";

export type GithubComRixlhqApiDbSqlcVideoQuality = "basic" | "shorts" | "pro";

/**
 * Standard error response returned by the API
 */
export type GithubComRixlhqApiInternalErrorsErrorResponse = {
  /**
   * HTTP status code
   */
  code?: number;
  /**
   * Optional details about the error
   */
  details?: string;
  /**
   * Error message describing what went wrong
   */
  error?: string;
};

export type GithubComRixlhqApiInternalVideosVideoResponse = {
  bitrate?: number;
  chapters?: Array<Chapter>;
  codec?: string;
  duration?: number;
  file?: File;
  framerate?: string;
  hdr?: boolean;
  height?: number;
  id?: string;
  plan_type?: GithubComRixlhqApiDbSqlcPlanType;
  poster?: Image;
  width?: number;
};

export type GithubComRixlhqApiInternalVideosHandlerUploadCompleteRequest = {
  video_id?: string;
};

export type GithubComRixlhqApiInternalVideosHandlerUploadInitResponse = {
  poster_id?: string;
  poster_presigned_url?: string;
  upload_expires?: number;
  video_id?: string;
  video_presigned_url?: string;
};

export type GithubComRixlhqApiInternalVideosTypesChapterInput = {
  start_time_sec?: number;
  title?: string;
};

export type InternalImagesHandlerCompleteRequest = {
  attached_to_video?: boolean;
  image_id?: string;
};

export type InternalImagesHandlerInitResponse = {
  image_id?: string;
  presigned_url?: string;
  upload_expires?: number;
};

export type InternalImagesHandlerUploadInitRequest = {
  format?: string;
  name?: string;
};

export type InternalVideosHandlerSubtitlesLanguageResponse = {
  code?: string;
  name?: string;
};

export type PaginationPaginatedResponseImage = {
  /**
   * Data contains the slice of items for the current request.
   */
  data?: Array<Image>;
  /**
   * Pagination data for the request.
   */
  pagination?: PaginationPagination;
};

export type PaginationPaginatedResponsePost = {
  /**
   * Data contains the slice of items for the current request.
   */
  data?: Array<Post>;
  /**
   * Pagination data for the request.
   */
  pagination?: PaginationPagination;
};

export type PaginationPaginatedResponseVideo = {
  /**
   * Data contains the slice of items for the current request.
   */
  data?: Array<Video>;
  /**
   * Pagination data for the request.
   */
  pagination?: PaginationPagination;
};

export type PaginationPagination = {
  /**
   * Maximum number of items to return in a single request.
   */
  limit?: number;
  /**
   * Starting point of the result set.
   */
  offset?: number;
  /**
   * The total number of available items in the full list.
   */
  total?: number;
};

export type GetFeedsByFeedIdData = {
  body?: never;
  path: {
    /**
     * Feed ID
     */
    feedId: string;
  };
  query?: {
    /**
     * Maximum number of items to return in a single request. <br> **Default:** `25`
     */
    limit?: number;
    /**
     * Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
     */
    offset?: number;
  };
  url: "/feeds/{feedId}";
};

export type GetFeedsByFeedIdErrors = {
  /**
   * Invalid feed ID or query parameters
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal server error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type GetFeedsByFeedIdError = GetFeedsByFeedIdErrors[keyof GetFeedsByFeedIdErrors];

export type GetFeedsByFeedIdResponses = {
  /**
   * OK
   */
  200: PaginationPaginatedResponsePost;
};

export type GetFeedsByFeedIdResponse = GetFeedsByFeedIdResponses[keyof GetFeedsByFeedIdResponses];

export type GetFeedsByFeedIdByPostIdData = {
  body?: never;
  path: {
    /**
     * Feed ID
     */
    feedId: string;
    /**
     * Post ID
     */
    postId: string;
  };
  query?: never;
  url: "/feeds/{feedId}/{postId}";
};

export type GetFeedsByFeedIdByPostIdErrors = {
  /**
   * Bad Request
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Not Found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type GetFeedsByFeedIdByPostIdError = GetFeedsByFeedIdByPostIdErrors[keyof GetFeedsByFeedIdByPostIdErrors];

export type GetFeedsByFeedIdByPostIdResponses = {
  /**
   * OK
   */
  200: Post;
};

export type GetFeedsByFeedIdByPostIdResponse = GetFeedsByFeedIdByPostIdResponses[keyof GetFeedsByFeedIdByPostIdResponses];

export type GetFeedsByFeedIdCreatorsByCreatorIdData = {
  body?: never;
  path: {
    /**
     * Feed ID
     */
    feedId: string;
    /**
     * Creator ID
     */
    creatorId: string;
  };
  query?: {
    /**
     * Maximum number of items to return in a single request. <br> **Default:** `25`
     */
    limit?: number;
    /**
     * Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
     */
    offset?: number;
  };
  url: "/feeds/{feedId}/creators/{creatorId}";
};

export type GetFeedsByFeedIdCreatorsByCreatorIdErrors = {
  /**
   * Invalid feed ID, creator ID, or query parameters
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal server error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type GetFeedsByFeedIdCreatorsByCreatorIdError =
  GetFeedsByFeedIdCreatorsByCreatorIdErrors[keyof GetFeedsByFeedIdCreatorsByCreatorIdErrors];

export type GetFeedsByFeedIdCreatorsByCreatorIdResponses = {
  /**
   * OK
   */
  200: PaginationPaginatedResponsePost;
};

export type GetFeedsByFeedIdCreatorsByCreatorIdResponse =
  GetFeedsByFeedIdCreatorsByCreatorIdResponses[keyof GetFeedsByFeedIdCreatorsByCreatorIdResponses];

export type GetImagesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of items to return in a single request. <br> **Default:** `25`
     */
    limit?: number;
    /**
     * Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
     */
    offset?: number;
    /**
     * Field to sort by (created_at, name, size, updated_at)
     */
    sort?: string;
    /**
     * Sort order (asc, desc)
     */
    order?: string;
  };
  url: "/images";
};

export type GetImagesErrors = {
  /**
   * Invalid query parameters
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Forbidden
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal server error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type GetImagesError = GetImagesErrors[keyof GetImagesErrors];

export type GetImagesResponses = {
  /**
   * OK
   */
  200: PaginationPaginatedResponseImage;
};

export type GetImagesResponse = GetImagesResponses[keyof GetImagesResponses];

export type DeleteImagesByImageIdData = {
  body?: never;
  path: {
    /**
     * Image ID
     */
    imageId: string;
  };
  query?: never;
  url: "/images/{imageId}";
};

export type DeleteImagesByImageIdErrors = {
  /**
   * Invalid project ID or image ID
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Image not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to delete image
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type DeleteImagesByImageIdError = DeleteImagesByImageIdErrors[keyof DeleteImagesByImageIdErrors];

export type DeleteImagesByImageIdResponses = {
  /**
   * Image deleted successfully
   */
  204: void;
};

export type DeleteImagesByImageIdResponse = DeleteImagesByImageIdResponses[keyof DeleteImagesByImageIdResponses];

export type GetImagesByImageIdData = {
  body?: never;
  path: {
    /**
     * Image ID
     */
    imageId: string;
  };
  query?: never;
  url: "/images/{imageId}";
};

export type GetImagesByImageIdErrors = {
  /**
   * Invalid image ID
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Forbidden
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Image not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal server error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type GetImagesByImageIdError = GetImagesByImageIdErrors[keyof GetImagesByImageIdErrors];

export type GetImagesByImageIdResponses = {
  /**
   * OK
   */
  200: Image;
};

export type GetImagesByImageIdResponse = GetImagesByImageIdResponses[keyof GetImagesByImageIdResponses];

export type PostImagesUploadCompleteData = {
  /**
   * Upload completion request
   */
  body: InternalImagesHandlerCompleteRequest;
  path?: never;
  query?: never;
  url: "/images/upload/complete";
};

export type PostImagesUploadCompleteErrors = {
  /**
   * Invalid request body
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized - Invalid API key
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * File not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to complete upload or create image
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type PostImagesUploadCompleteError = PostImagesUploadCompleteErrors[keyof PostImagesUploadCompleteErrors];

export type PostImagesUploadCompleteResponses = {
  /**
   * OK
   */
  200: Image;
};

export type PostImagesUploadCompleteResponse = PostImagesUploadCompleteResponses[keyof PostImagesUploadCompleteResponses];

export type PostImagesUploadInitData = {
  /**
   * Upload initialization request
   */
  body: InternalImagesHandlerUploadInitRequest;
  path?: never;
  query?: never;
  url: "/images/upload/init";
};

export type PostImagesUploadInitErrors = {
  /**
   * Invalid request body
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized - Invalid API key
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to initialize upload
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type PostImagesUploadInitError = PostImagesUploadInitErrors[keyof PostImagesUploadInitErrors];

export type PostImagesUploadInitResponses = {
  /**
   * OK
   */
  200: InternalImagesHandlerInitResponse;
};

export type PostImagesUploadInitResponse = PostImagesUploadInitResponses[keyof PostImagesUploadInitResponses];

export type GetVideosData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of items to return in a single request. <br> **Default:** `25`
     */
    limit?: number;
    /**
     * Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
     */
    offset?: number;
    /**
     * Field to sort by (created_at, name, size, updated_at, duration)
     */
    sort?: string;
    /**
     * Sort order (asc, desc)
     */
    order?: string;
  };
  url: "/videos";
};

export type GetVideosErrors = {
  /**
   * Invalid query parameters
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Forbidden
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal server error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type GetVideosError = GetVideosErrors[keyof GetVideosErrors];

export type GetVideosResponses = {
  /**
   * OK
   */
  200: PaginationPaginatedResponseVideo;
};

export type GetVideosResponse = GetVideosResponses[keyof GetVideosResponses];

export type GetVideosByVideoIdData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}";
};

export type GetVideosByVideoIdErrors = {
  /**
   * Invalid video ID
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Forbidden
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Video not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal server error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type GetVideosByVideoIdError = GetVideosByVideoIdErrors[keyof GetVideosByVideoIdErrors];

export type GetVideosByVideoIdResponses = {
  /**
   * OK
   */
  200: Video;
};

export type GetVideosByVideoIdResponse = GetVideosByVideoIdResponses[keyof GetVideosByVideoIdResponses];

export type DeleteVideosByVideoIdAudioTracksData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/audio-tracks";
};

export type DeleteVideosByVideoIdAudioTracksResponses = {
  /**
   * OK
   */
  200: AudioTrackDelete;
};

export type DeleteVideosByVideoIdAudioTracksResponse =
  DeleteVideosByVideoIdAudioTracksResponses[keyof DeleteVideosByVideoIdAudioTracksResponses];

export type PostVideosByVideoIdAudioTracksData = {
  /**
   * files | Comma-separated language codes | Comma-separated labels
   */
  body: {
    /**
     * files
     */
    files: Array<string>;
    /**
     * Comma-separated labels
     */
    labels: string;
    /**
     * Comma-separated language codes
     */
    language_codes: string;
  };
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/audio-tracks";
};

export type PostVideosByVideoIdAudioTracksResponses = {
  /**
   * OK
   */
  200: Array<AudioTrack>;
};

export type PostVideosByVideoIdAudioTracksResponse = PostVideosByVideoIdAudioTracksResponses[keyof PostVideosByVideoIdAudioTracksResponses];

export type DeleteVideosByVideoIdAudioTracksByTrackIdData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
    /**
     * Audio Track ID
     */
    trackId: string;
  };
  query?: never;
  url: "/videos/{videoId}/audio-tracks/{trackId}";
};

export type DeleteVideosByVideoIdAudioTracksByTrackIdErrors = {
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Forbidden
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Not Found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal Server Error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type DeleteVideosByVideoIdAudioTracksByTrackIdError =
  DeleteVideosByVideoIdAudioTracksByTrackIdErrors[keyof DeleteVideosByVideoIdAudioTracksByTrackIdErrors];

export type DeleteVideosByVideoIdAudioTracksByTrackIdResponses = {
  /**
   * OK
   */
  200: AudioTrackDelete;
};

export type DeleteVideosByVideoIdAudioTracksByTrackIdResponse =
  DeleteVideosByVideoIdAudioTracksByTrackIdResponses[keyof DeleteVideosByVideoIdAudioTracksByTrackIdResponses];

export type DeleteVideosByVideoIdAudioTracksLanguageByLangCodeData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
    /**
     * Language Code (BCP 47)
     */
    lang_code: string;
  };
  query?: never;
  url: "/videos/{videoId}/audio-tracks/language/{lang_code}";
};

export type DeleteVideosByVideoIdAudioTracksLanguageByLangCodeResponses = {
  /**
   * OK
   */
  200: AudioTrackDelete;
};

export type DeleteVideosByVideoIdAudioTracksLanguageByLangCodeResponse =
  DeleteVideosByVideoIdAudioTracksLanguageByLangCodeResponses[keyof DeleteVideosByVideoIdAudioTracksLanguageByLangCodeResponses];

export type PutVideosByVideoIdAudioTracksLanguageByLangCodeData = {
  /**
   * file | Label (e.g. English)
   */
  body: {
    /**
     * file
     */
    file: Blob | File;
    /**
     * Label (e.g. English)
     */
    label?: string;
  };
  path: {
    /**
     * Video ID
     */
    videoId: string;
    /**
     * Language Code (BCP 47)
     */
    lang_code: string;
  };
  query?: never;
  url: "/videos/{videoId}/audio-tracks/language/{lang_code}";
};

export type PutVideosByVideoIdAudioTracksLanguageByLangCodeResponses = {
  /**
   * OK
   */
  200: AudioTrack;
};

export type PutVideosByVideoIdAudioTracksLanguageByLangCodeResponse =
  PutVideosByVideoIdAudioTracksLanguageByLangCodeResponses[keyof PutVideosByVideoIdAudioTracksLanguageByLangCodeResponses];

export type DeleteVideosByVideoIdChaptersData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/chapters";
};

export type DeleteVideosByVideoIdChaptersErrors = {
  /**
   * Unauthorized - Invalid API key
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Video not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to delete chapters
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type DeleteVideosByVideoIdChaptersError = DeleteVideosByVideoIdChaptersErrors[keyof DeleteVideosByVideoIdChaptersErrors];

export type DeleteVideosByVideoIdChaptersResponses = {
  /**
   * OK
   */
  200: UpdateChaptersResponse;
};

export type DeleteVideosByVideoIdChaptersResponse = DeleteVideosByVideoIdChaptersResponses[keyof DeleteVideosByVideoIdChaptersResponses];

export type PutVideosByVideoIdChaptersData = {
  /**
   * Chapters array
   */
  body: UpdateChaptersRequest;
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/chapters";
};

export type PutVideosByVideoIdChaptersErrors = {
  /**
   * Invalid request body or video duration not available
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized - Invalid API key
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Video not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to update chapters
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type PutVideosByVideoIdChaptersError = PutVideosByVideoIdChaptersErrors[keyof PutVideosByVideoIdChaptersErrors];

export type PutVideosByVideoIdChaptersResponses = {
  /**
   * OK
   */
  200: UpdateChaptersResponse;
};

export type PutVideosByVideoIdChaptersResponse = PutVideosByVideoIdChaptersResponses[keyof PutVideosByVideoIdChaptersResponses];

export type DeleteVideosByVideoIdDeleteData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/delete";
};

export type DeleteVideosByVideoIdDeleteErrors = {
  /**
   * Invalid project ID or video ID
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Video not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to delete video
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type DeleteVideosByVideoIdDeleteError = DeleteVideosByVideoIdDeleteErrors[keyof DeleteVideosByVideoIdDeleteErrors];

export type DeleteVideosByVideoIdDeleteResponses = {
  /**
   * Video deleted successfully
   */
  204: void;
};

export type DeleteVideosByVideoIdDeleteResponse = DeleteVideosByVideoIdDeleteResponses[keyof DeleteVideosByVideoIdDeleteResponses];

export type DeleteVideosByVideoIdSubtitlesData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/subtitles";
};

export type DeleteVideosByVideoIdSubtitlesResponses = {
  /**
   * OK
   */
  200: SubtitleDelete;
};

export type DeleteVideosByVideoIdSubtitlesResponse = DeleteVideosByVideoIdSubtitlesResponses[keyof DeleteVideosByVideoIdSubtitlesResponses];

export type PostVideosByVideoIdSubtitlesData = {
  /**
   * files | Comma-separated language codes | Comma-separated labels
   */
  body: {
    /**
     * files
     */
    files: Array<string>;
    /**
     * Comma-separated labels
     */
    labels: string;
    /**
     * Comma-separated language codes
     */
    language_codes: string;
  };
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/subtitles";
};

export type PostVideosByVideoIdSubtitlesResponses = {
  /**
   * OK
   */
  200: Array<Subtitle>;
};

export type PostVideosByVideoIdSubtitlesResponse = PostVideosByVideoIdSubtitlesResponses[keyof PostVideosByVideoIdSubtitlesResponses];

export type DeleteVideosByVideoIdSubtitlesBySubtitleIdData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
    /**
     * Subtitle ID
     */
    subtitleId: string;
  };
  query?: never;
  url: "/videos/{videoId}/subtitles/{subtitleId}";
};

export type DeleteVideosByVideoIdSubtitlesBySubtitleIdErrors = {
  /**
   * Unauthorized
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Forbidden
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Not Found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Internal Server Error
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type DeleteVideosByVideoIdSubtitlesBySubtitleIdError =
  DeleteVideosByVideoIdSubtitlesBySubtitleIdErrors[keyof DeleteVideosByVideoIdSubtitlesBySubtitleIdErrors];

export type DeleteVideosByVideoIdSubtitlesBySubtitleIdResponses = {
  /**
   * OK
   */
  200: SubtitleDelete;
};

export type DeleteVideosByVideoIdSubtitlesBySubtitleIdResponse =
  DeleteVideosByVideoIdSubtitlesBySubtitleIdResponses[keyof DeleteVideosByVideoIdSubtitlesBySubtitleIdResponses];

export type DeleteVideosByVideoIdSubtitlesLanguageByLangCodeData = {
  body?: never;
  path: {
    /**
     * Video ID
     */
    videoId: string;
    /**
     * Language Code (BCP 47)
     */
    lang_code: string;
  };
  query?: never;
  url: "/videos/{videoId}/subtitles/language/{lang_code}";
};

export type DeleteVideosByVideoIdSubtitlesLanguageByLangCodeResponses = {
  /**
   * OK
   */
  200: SubtitleDelete;
};

export type DeleteVideosByVideoIdSubtitlesLanguageByLangCodeResponse =
  DeleteVideosByVideoIdSubtitlesLanguageByLangCodeResponses[keyof DeleteVideosByVideoIdSubtitlesLanguageByLangCodeResponses];

export type PutVideosByVideoIdSubtitlesLanguageByLangCodeData = {
  /**
   * file | Label (e.g. English)
   */
  body: {
    /**
     * file
     */
    file: Blob | File;
    /**
     * Label (e.g. English)
     */
    label?: string;
  };
  path: {
    /**
     * Video ID
     */
    videoId: string;
    /**
     * Language Code (BCP 47)
     */
    lang_code: string;
  };
  query?: never;
  url: "/videos/{videoId}/subtitles/language/{lang_code}";
};

export type PutVideosByVideoIdSubtitlesLanguageByLangCodeResponses = {
  /**
   * OK
   */
  200: Subtitle;
};

export type PutVideosByVideoIdSubtitlesLanguageByLangCodeResponse =
  PutVideosByVideoIdSubtitlesLanguageByLangCodeResponses[keyof PutVideosByVideoIdSubtitlesLanguageByLangCodeResponses];

export type PutVideosByVideoIdThumbnailData = {
  /**
   * file
   */
  body: {
    /**
     * file
     */
    thumbnail: Blob | File;
  };
  path: {
    /**
     * Video ID
     */
    videoId: string;
  };
  query?: never;
  url: "/videos/{videoId}/thumbnail";
};

export type PutVideosByVideoIdThumbnailErrors = {
  /**
   * Invalid file or request
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized - Invalid API key
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Video not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Upload or update failed
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type PutVideosByVideoIdThumbnailError = PutVideosByVideoIdThumbnailErrors[keyof PutVideosByVideoIdThumbnailErrors];

export type PutVideosByVideoIdThumbnailResponses = {
  /**
   * Video with updated thumbnail
   */
  200: Video;
};

export type PutVideosByVideoIdThumbnailResponse = PutVideosByVideoIdThumbnailResponses[keyof PutVideosByVideoIdThumbnailResponses];

export type GetVideosLanguagesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/videos/languages";
};

export type GetVideosLanguagesResponses = {
  /**
   * OK
   */
  200: Array<InternalVideosHandlerSubtitlesLanguageResponse>;
};

export type GetVideosLanguagesResponse = GetVideosLanguagesResponses[keyof GetVideosLanguagesResponses];

export type PostVideosUploadCompleteData = {
  /**
   * Video upload completion request
   */
  body: GithubComRixlhqApiInternalVideosHandlerUploadCompleteRequest;
  path?: never;
  query?: never;
  url: "/videos/upload/complete";
};

export type PostVideosUploadCompleteErrors = {
  /**
   * Invalid request body
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized - Invalid API key
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * File not found
   */
  404: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to complete upload
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type PostVideosUploadCompleteError = PostVideosUploadCompleteErrors[keyof PostVideosUploadCompleteErrors];

export type PostVideosUploadCompleteResponses = {
  /**
   * OK
   */
  200: Video;
};

export type PostVideosUploadCompleteResponse = PostVideosUploadCompleteResponses[keyof PostVideosUploadCompleteResponses];

export type PostVideosUploadInitData = {
  /**
   * Video upload initialization request
   */
  body: VideoUploadInitRequest;
  path?: never;
  query?: never;
  url: "/videos/upload/init";
};

export type PostVideosUploadInitErrors = {
  /**
   * Invalid request body
   */
  400: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Unauthorized - Invalid API key
   */
  401: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Access denied
   */
  403: GithubComRixlhqApiInternalErrorsErrorResponse;
  /**
   * Failed to initialize upload
   */
  500: GithubComRixlhqApiInternalErrorsErrorResponse;
};

export type PostVideosUploadInitError = PostVideosUploadInitErrors[keyof PostVideosUploadInitErrors];

export type PostVideosUploadInitResponses = {
  /**
   * OK
   */
  200: GithubComRixlhqApiInternalVideosHandlerUploadInitResponse;
};

export type PostVideosUploadInitResponse = PostVideosUploadInitResponses[keyof PostVideosUploadInitResponses];
