/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Chapter from './Chapter';

/**
 * The UpdateChaptersResponse model module.
 * @module model/UpdateChaptersResponse
 * @version 2.0
 */
class UpdateChaptersResponse {
    /**
     * Constructs a new <code>UpdateChaptersResponse</code>.
     * @alias module:model/UpdateChaptersResponse
     */
    constructor() { 
        
        UpdateChaptersResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateChaptersResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateChaptersResponse} obj Optional instance to populate.
     * @return {module:model/UpdateChaptersResponse} The populated <code>UpdateChaptersResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateChaptersResponse();

            if (data.hasOwnProperty('chapters')) {
                obj['chapters'] = ApiClient.convertToType(data['chapters'], [Chapter]);
            }
            if (data.hasOwnProperty('video_id')) {
                obj['video_id'] = ApiClient.convertToType(data['video_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateChaptersResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateChaptersResponse</code>.
     */
    static validateJSON(data) {
        if (data['chapters']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['chapters'])) {
                throw new Error("Expected the field `chapters` to be an array in the JSON data but got " + data['chapters']);
            }
            // validate the optional field `chapters` (array)
            for (const item of data['chapters']) {
                Chapter.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['video_id'] && !(typeof data['video_id'] === 'string' || data['video_id'] instanceof String)) {
            throw new Error("Expected the field `video_id` to be a primitive type in the JSON string but got " + data['video_id']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Chapter>} chapters
 */
UpdateChaptersResponse.prototype['chapters'] = undefined;

/**
 * @member {String} video_id
 */
UpdateChaptersResponse.prototype['video_id'] = undefined;






export default UpdateChaptersResponse;

