/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GithubComQeeqezApiInternalVideosTypesChapterInput from './GithubComQeeqezApiInternalVideosTypesChapterInput';

/**
 * The UpdateChaptersRequest model module.
 * @module model/UpdateChaptersRequest
 * @version 2.0
 */
class UpdateChaptersRequest {
    /**
     * Constructs a new <code>UpdateChaptersRequest</code>.
     * @alias module:model/UpdateChaptersRequest
     */
    constructor() { 
        
        UpdateChaptersRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateChaptersRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateChaptersRequest} obj Optional instance to populate.
     * @return {module:model/UpdateChaptersRequest} The populated <code>UpdateChaptersRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateChaptersRequest();

            if (data.hasOwnProperty('chapters')) {
                obj['chapters'] = ApiClient.convertToType(data['chapters'], [GithubComQeeqezApiInternalVideosTypesChapterInput]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateChaptersRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateChaptersRequest</code>.
     */
    static validateJSON(data) {
        if (data['chapters']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['chapters'])) {
                throw new Error("Expected the field `chapters` to be an array in the JSON data but got " + data['chapters']);
            }
            // validate the optional field `chapters` (array)
            for (const item of data['chapters']) {
                GithubComQeeqezApiInternalVideosTypesChapterInput.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/GithubComQeeqezApiInternalVideosTypesChapterInput>} chapters
 */
UpdateChaptersRequest.prototype['chapters'] = undefined;






export default UpdateChaptersRequest;

