/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RixlApi);
  }
}(this, function(expect, RixlApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RixlApi.VideosApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VideosApi', function() {
    describe('videosGet', function() {
      it('should call videosGet successfully', function(done) {
        //uncomment below and update the code to test videosGet
        //instance.videosGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosLanguagesGet', function() {
      it('should call videosLanguagesGet successfully', function(done) {
        //uncomment below and update the code to test videosLanguagesGet
        //instance.videosLanguagesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosUploadCompletePost', function() {
      it('should call videosUploadCompletePost successfully', function(done) {
        //uncomment below and update the code to test videosUploadCompletePost
        //instance.videosUploadCompletePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosUploadInitPost', function() {
      it('should call videosUploadInitPost successfully', function(done) {
        //uncomment below and update the code to test videosUploadInitPost
        //instance.videosUploadInitPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdAudioTracksDelete', function() {
      it('should call videosVideoIdAudioTracksDelete successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdAudioTracksDelete
        //instance.videosVideoIdAudioTracksDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdAudioTracksLangCodeDelete', function() {
      it('should call videosVideoIdAudioTracksLangCodeDelete successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdAudioTracksLangCodeDelete
        //instance.videosVideoIdAudioTracksLangCodeDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdAudioTracksLangCodePut', function() {
      it('should call videosVideoIdAudioTracksLangCodePut successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdAudioTracksLangCodePut
        //instance.videosVideoIdAudioTracksLangCodePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdAudioTracksPost', function() {
      it('should call videosVideoIdAudioTracksPost successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdAudioTracksPost
        //instance.videosVideoIdAudioTracksPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdAudioTracksTrackIdDelete', function() {
      it('should call videosVideoIdAudioTracksTrackIdDelete successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdAudioTracksTrackIdDelete
        //instance.videosVideoIdAudioTracksTrackIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdChaptersDelete', function() {
      it('should call videosVideoIdChaptersDelete successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdChaptersDelete
        //instance.videosVideoIdChaptersDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdChaptersPut', function() {
      it('should call videosVideoIdChaptersPut successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdChaptersPut
        //instance.videosVideoIdChaptersPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdDeleteDelete', function() {
      it('should call videosVideoIdDeleteDelete successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdDeleteDelete
        //instance.videosVideoIdDeleteDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdGet', function() {
      it('should call videosVideoIdGet successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdGet
        //instance.videosVideoIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdSubtitlesDelete', function() {
      it('should call videosVideoIdSubtitlesDelete successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdSubtitlesDelete
        //instance.videosVideoIdSubtitlesDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdSubtitlesLangCodeDelete', function() {
      it('should call videosVideoIdSubtitlesLangCodeDelete successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdSubtitlesLangCodeDelete
        //instance.videosVideoIdSubtitlesLangCodeDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdSubtitlesLangCodePut', function() {
      it('should call videosVideoIdSubtitlesLangCodePut successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdSubtitlesLangCodePut
        //instance.videosVideoIdSubtitlesLangCodePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdSubtitlesPost', function() {
      it('should call videosVideoIdSubtitlesPost successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdSubtitlesPost
        //instance.videosVideoIdSubtitlesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdSubtitlesSubtitleIdDelete', function() {
      it('should call videosVideoIdSubtitlesSubtitleIdDelete successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdSubtitlesSubtitleIdDelete
        //instance.videosVideoIdSubtitlesSubtitleIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videosVideoIdThumbnailPut', function() {
      it('should call videosVideoIdThumbnailPut successfully', function(done) {
        //uncomment below and update the code to test videosVideoIdThumbnailPut
        //instance.videosVideoIdThumbnailPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
